# 係数行列の圧縮を行う

参考 : https://stackoverflow.com/questions/28816627/how-to-find-linearly-independent-rows-from-a-matrix

In [45]:
import instances
import importlib
importlib.reload(instances)
Customers = instances.Customers
Points = instances.Points
C, F = instances.C, instances.F
tour = instances.tour

instance_name = "C" + str(len(Customers)-1)

In [46]:
import inputs
As, Ac_eq, Ac_leq, Ar_eq, Ar_leq, Ap, Aq, b_eq, b_leq, op, oq = inputs.make_inputs(tour, Customers, Points, F, C)

Preceding constraints are done.
Time-window constarints are done.
Pick-up and delivery constarints are done.
Charge constarints are done.


In [52]:
# Asに他の係数行列をくっつける
import numpy as np
A_leq = np.array([np.array([]) for _ in range(len(As))])
for i in range(len(As)):
    A_leq[i] = As[i] + Ac_leq[i]
    A_leq[i] = As[i] + Ar_leq[i]
    A_leq[i] = As[i] + Ap[i]
    A_leq[i] = As[i] + Aq[i]
    A_leq[i] = np.append(As[i], b_leq[i])

ValueError: could not broadcast input array from shape (6,) into shape (0,)

In [48]:
for row in A_leq:
    print(row)

[ 2 -1  0  0  0  0]
[ 0  2 -1  0  0  0]
[ 0  0  2 -1  0  0]
[ 0  0  0  2 -1  0]
[ 0  0  0  0  2 -1]
[-2  0  0  0  0  0]
[0 0 0 0 0 0]
[ 0 -2  0  0  0  0]
[0 0 0 0 0 0]
[ 0  0 -2  0  0  0]
[0 0 0 0 0 0]
[ 0  0  0 -2  0  0]
[0 0 0 0 0 0]
[ 0  0  0  0 -2  0]
[0 0 0 0 0 0]
[ 0  0  0  0  0 -2]
[0 0 0 0 0 0]
[ 0  0 -2  0  1  0]
[2 0 0 0 0 0]
[0 2 0 0 0 0]
[0 0 2 0 0 0]
[0 0 0 2 0 0]
[0 0 0 0 2 0]
[0 0 0 0 0 2]


In [154]:
from numpy.linalg import matrix_rank

def LI_vecs(dim,M):
    LI=[M[0]]
    for i in range(dim):
        tmp=[]
        for r in LI:
            tmp.append(r)
        tmp.append(M[i])                #set tmp=LI+[M[i]]
        if matrix_rank(tmp)>len(LI):    #test if M[i] is linearly independent from all (row) vectors in LI
            LI.append(M[i])             #note that matrix_rank does not need to take in a square matrix
    return LI                           #return set of linearly independent (row) vectors

#Example
#mat=[[1,2,3,4],[4,5,6,7],[5,7,9,11],[2,4,6,8]]
#LI_vecs(4,mat)

[[1, 2, 3, 4], [4, 5, 6, 7]]

In [155]:
A_leq_compressed = LI_vecs(len(A_leq), A_leq)

In [156]:
len(A_leq)

17

In [157]:
len(A_leq_compressed)

17

In [158]:
for row in A_leq_compressed:
    print(row)

[1, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -2.23606797749979]
[0, 1, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -2.23606797749979]
[0, 0, 1, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -3.1622776601683795]
[0, 0, 0, 1, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -9.899494936611665]
[0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -9.055385138137417]
[-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]
[0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -4]
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6]
[0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

# 全てのものを繋げて圧縮を行おうとしたが、うまく圧縮できない

# そこで、制約の種類ごとに係数行列をまとめて、圧縮を行う必要があると思う

例えば、訪問順序に関する制約ならば、As、Ac_leq、b_leqをまとめる。そして圧縮する。

In [166]:
# Asにb_leqをつなげる
A_preceding = [[] for _ in range(len(As))]
for i in range(len(As)):
    A_preceding[i] += (Ac_leq[i])
    A_preceding[i] += (Ap[i])
    A_preceding[i].append(b_leq[i])

In [167]:
A_preceding_compressed = LI_vecs(len(As), As)

In [168]:
len(A_preceding)

17

In [169]:
len(A_preceding_compressed)

6