# ルートを評価するために解くLPについて
- ルートが1つ与えられた後、そのルートを評価するためにLPを解く(ルートが実行可能であるとは限らない)

<!--- 各制約の違反度を変数とし、それらに重みをかけて足し合わせた関数の最小化問題とする-->
- 車両が各顧客へ到着する時刻を変数とし、その合計を最小化する問題とする
- 制約は、容量制約と時間枠制約とする
    - 容量制約は、ある区間における2つの関数の積分値(面積)の大小を比較するという形で表す(車両の積荷の量を表す区分線形関数の\[x0, xn\]までの積分値と最大容量を表す線形関数の\[x0, xn\]までの積分値)
    - 時間枠制約は、通常のVRPの定式化と同様に表す


# 前準備

## 問題例の読み込み
使用した問題例 : https://neo.lcc.uma.es/vrp/vrp-instances/description-for-files-of-solomons-instances/

In [ ]:
class Customer():
    def __init__(self, x, y, d, e, l, s):
        self.x = x
        self.y = y
        self.d = d
        self.e = e
        self.l = l
        self.s = s

In [ ]:
import glob

files = glob.glob("./solomon_25/*")
for file in files:
    print(file)

In [ ]:
# 問題例の選択
instance = files[0]

In [ ]:
Customers = {}
with open(instance, mode="r") as f:
    for index,line in enumerate(f):
        #print(line)
        l = []
        if index==4:
            line_s = [s.strip("\n") for s in line.split("\t")][0]
            for s in line_s.split(" "):
                if s!="":
                    l.append(int(s))
            K, Q = l
        elif 9<=index<=34:
            line_s = [s.strip("\n") for s in line.split("\t")][0]
            for s in line_s.split(" "):
                if s!="":
                    l.append(int(s))
            Customers[l[0]] = Customer(*l[1:])

In [ ]:
Customers["depot"] = Customer(0,0,0,0,1000,0)

In [ ]:
print("\t", list(vars(Customers["depot"]).keys()))
for i in Customers.keys():
    print(i, end="\t")
    for key, val in vars(Customers[i]).items():
        print(val, end=" ")
    print()

## ルートの作成

In [ ]:
# 入力
## 顧客
C={} # 客の座標を保存する辞書
TW={} # 客の時間枠を保存する辞書
demand={} # 客の要求量(正の値は集荷，負の値は配達)
S={} # 客のサービス時間

for i in Customers:
    x, y = Customers[i].x, Customers[i].y
    C[i] = (x,y)
    e, l = Customers[i].e, Customers[i].l
    TW[i] = (e,l)
    demand[i] = (Customers[i].d, )
    S[i] = Customers[i].s
    """name="c"+str(i)
    x, y = Customers[i].x, Customers[i].y
    C[name] = (x,y)
    e, l = Customers[i].e, Customers[i].l
    TW[name] = (e,l)
    demand[name] = (Customers[i].d, )
    S[name] = Customers[i].s"""
#C["depot"]=(0,0)

## 車両
M = K//2 # number of vehicles
capacities = [(Q*2, ) for k in range(M)] # capacity of vehicle

In [ ]:
print("Customer",C)
print("Time Window",TW)
print("Demand",demand)
print("Service Time",S)

In [ ]:
import networkx as nx
import matplotlib.pyplot as plt

fig=plt.figure(figsize=(7,7))

G=nx.DiGraph()
nx.draw_networkx(G,pos=C,nodelist=[i for i in C if i != "depot"],node_color="y",node_size=50,with_labels=True,edge_color="k",width=1)
nx.draw_networkx(G,pos=C,nodelist=["depot"],node_color="blue",node_shape='s',alpha=0.5,node_size=100,with_labels=True,edge_color="k",width=1)

plt.show()

In [ ]:
# 距離関数の定義
#def Distance(t1,t2):
#    return ((t1[0]-t2[0])**2+(t1[1]-t2[1])**2)**(0.5)
def distance(x1, y1, x2, y2):
    return ((x2-x1)**2+(y2-y1)**2)**(0.5)

# ソルバーの読み込み
import sys
sys.path.append('..')

#from vrplib.vrp_d_1m1_t_model import *
import vrplib.vrp_d_1m1_t_model as vrp

# ソルバーの実行
model = vrp.Model(file.split("/")[-1].split(".")[0]) # モデルインスタンスの生成

## 客インスタンスの生成
for i in C:
    if i == "depot":
        continue
    model += vrp.Customer(i,demand=demand[i],timewindow=TW[i],servicetime=S[i])

## 車両インスタンスの生成
for k in range(M):
    model += vrp.Vehicle("v"+str(k),capacity=capacities[k])
    
## 枝インスタンスの生成
for i in C:
    for j in C:
        if i!=j:
            dist = time = distance(*C[i],*C[j])
            model += vrp.Edge(i,j,dist,time)

In [ ]:
## 最適化の実行
obj=model.optimize(IterLimit=10000,TimeLimit=10,Verbose=False,OutputFlag=False)

## 得られた解の表示
print("objective value =",obj)
for v in model.vehiclesL:
    print()
    print(v)
    print(list(map(lambda x:x.name,v.routing[1:-1])))    
    for iv in map(lambda x:x.name,v.routing[1:-1]):
        print(iv)

## ルートを1つ選ぶ

In [ ]:
# Vehicle 6の巡回路を選んでいる
tour = [12, 3, 24, 25]#+["depot"]

## その他作業

In [ ]:
# 使用した問題例の名称を保存
tmp = []
for s in instance[-1:0:-1]:
    if s=='/':
        break
    tmp.append(s)
instance_name = "".join(tmp[-1:0:-1])
print(instance_name)

# 前準備

## instances.pyからインスタンスを得る

In [1]:
import instances
Customers = instances.Customers
tour = instances.tour

In [2]:
instance_name = "C" + str(len(Customers)-1)

In [3]:
tour[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
tour[-10:]

[6312, 6313, 6314, 6315, 6316, 6317, 6318, 6319, 6320, 'depot']

# 問題を解く
2つの手法に対し、計算時間を比較

## 入力する行列、ベクトルの作成

In [5]:
def distance(x1, y1, x2, y2):
    return ((x2-x1)**2+(y2-y1)**2)**(0.5)

In [6]:
def make_preceding_constr(tour, Customers, Ax, Ap, b, c):
    # ルート内の顧客の順序に関する制約
    for index, i in enumerate(tour):
        try:
            i_next = tour[index+1]
        except:
            i_next = "depot"
            continue
        Ax.append([1 if target==i else -1 if target==i_next else 0 for target in tour])
        Ap.append([0 for _ in range(len(tour))])
        b.append(-distance(Customers[i].x, Customers[i].y, Customers[i_next].x, Customers[i_next].y))
    return Ax, Ap, b, c

In [7]:
def make_tw_constr(tour, Customers, Ax, Ap, b, c):
    # 時間枠制約
    for index, i in enumerate(tour):
        Ax.append([-1 if i==target else 0 for index_, target in enumerate(tour)])
        Ap.append([-1 if i==target else 0 for index_, target in enumerate(tour)])
        b.append(-Customers[i].e)
        Ax.append([1 if i==target else 0 for index_, target in enumerate(tour)])
        Ap.append([-1 if i==target else 0 for index_, target in enumerate(tour)])
        b.append(Customers[i].l)
    return Ax, Ap, b, c

In [8]:
def make_inputs(tour, Customers):
    import numpy as np
    Ax, Ap, b, c = [], [], [], [1 for _ in range(len(tour))]
    # ルート内の顧客の順序に関する制約
    Ax, Ap, b, c = make_preceding_constr(tour, Customers, Ax, Ap, b, c)
    print("Preceding constraints are done.")
    # 時間枠制約
    Ax, Ap, b, c = make_tw_constr(tour, Customers, Ax, Ap, b, c)
    print("Time-window constarints are done.")
    # ndarrayに変換
    Ax = np.array(Ax)
    Ap = np.array(Ap)
    b = np.array(b)
    c = np.array(c)
    return Ax, Ap, b, c

## 主問題を解く関数の定義
与えられた定数を元にLPのモデルを作成した上でそれを解き、最適解を返す関数

In [9]:
def solve_primal(Ax, Ap, b, c, instance_name, num_vars):
    import gurobipy as gp
    from gurobipy import GRB
    import numpy as np
    import time
    
    # インスタンスの生成
    m = gp.Model("LP_for_VRP" + instance_name)
    # 定数を設定　←　入力として与えられる
    # 変数を設定
    """
    x_i : 顧客iへ車両が到着する時刻を表す変数
    p_i : 顧客iの時間枠の違反度を表す変数
    """
    x = m.addMVar(shape=num_vars, vtype=GRB.CONTINUOUS, name="x")
    p = m.addMVar(shape=num_vars, vtype=GRB.CONTINUOUS, name="p")

    # モデルのアップデート
    m.update()
    
    # 目的関数を設定
    ## 各制約の違反度を最小化する
    m.setObjective(c.T @ p, sense=gp.GRB.MINIMIZE)
    
    # 制約条件を設定
    m.addConstr(Ax @ x + Ap @ p <= b, name="c")

    # モデルのアップデート
    m.update()
    
    # 時間計測スタート
    start = time.time()
    
    # 最適化
    m.optimize()
    
    # 時間計測ストップ
    elapsed_time = time.time() - start
    
    # 解の表示
    if m.Status == gp.GRB.OPTIMAL:
        for i in range(num_vars):
            print(f"車両が顧客{i}に到着する時刻は、{x[i].X}")
        print("最適値 : ", m.ObjVal)
    print('\033[34m'+f"実時間\t{elapsed_time}"+'\033[0m')
        
    return m

## 双対問題を解く関数の定義

In [10]:
def solve_dual(Ax, Ap, b, c, instance_name, num_vars, basis_like):
    import gurobipy as gp
    from gurobipy import GRB
    import numpy as np
    import time
    
    # インスタンスの生成
    m = gp.Model("LP_for_VRP" + instance_name)
    
    # 変数を設定
    """
    y_i : 主問題における制約式iの潜在価値
    """
    y = m.addMVar(shape=num_vars, vtype=GRB.CONTINUOUS, name="y")

    # モデルのアップデート
    m.update()
    
    # 目的関数を設定
    ## 各制約の違反度を最小化する
    m.setObjective(-1 * b.T @ y, sense=gp.GRB.MAXIMIZE)
    
    # 制約条件を設定
    m.addConstr(Ax.T @ y >= 0, name="c1")
    m.addConstr(Ap.T @ y + c >= 0, name="c2")
    m.addConstr(y >= 0, name="c3")

    # モデルのアップデート
    m.update()
    
    # 時間計測スタート
    start = time.time()
    
    # ホットスタートの使用
    for i in range(num_vars):
        y[i].PStart = basis_like[i]
    
    # 最適化
    m.optimize()
    
    # 時間計測ストップ
    elapsed_time = time.time() - start
    
    # 解の表示
    if m.Status == gp.GRB.OPTIMAL:
        for i in range(num_vars):
            print(f"主問題における制約{i}の潜在価格は、{y[i].X}")
        print("最適値 : ", m.ObjVal)
    print('\033[34m'+f"実時間\t{elapsed_time}"+'\033[0m')
        
    return m

## ①全体を1つのLPとして解くveb.

### 全体のPrimalを解く

In [11]:
Ax, Ap, b, c = make_inputs(tour, Customers)

Preceding constraints are done.
Time-window constarints are done.


In [12]:
# Gurobiによって最適解を求める
whole_x = solve_primal(Ax, Ap, b, c, instance_name+"whole_x", len(tour))

Using license file /Users/okamoto/gurobi.lic
Academic license - for non-commercial use only
Gurobi Optimizer version 9.0.2 build v9.0.2rc0 (mac64)
Optimize a model with 18965 rows, 12644 columns and 37930 nonzeros
Model fingerprint: 0xa123105c
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 2e+04]

Concurrent LP optimizer: dual simplex and barrier
Showing barrier log only...

Presolve removed 12583 rows and 6264 columns
Presolve time: 0.17s
Presolved: 6382 rows, 6380 columns, 12764 nonzeros

Ordering time: 0.00s

Barrier statistics:
 Dense cols : 32
 AA' NZ     : 1.527e+04
 Factor NZ  : 2.243e+04 (roughly 5 MBytes of memory)
 Factor Ops : 2.991e+05 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   1.50373673e+08 -1.00000000e+03  1.06e+04 0.00e+00  1.

車両が顧客144に到着する時刻は、[882.88926012]
車両が顧客145に到着する時刻は、[887.88926012]
車両が顧客146に到着する時刻は、[892.1319008]
車両が顧客147に到着する時刻は、[894.36796878]
車両が顧客148に到着する時刻は、[903.80194991]
車両が顧客149に到着する時刻は、[909.45880416]
車両が顧客150に到着する時刻は、[911.45880416]
車両が顧客151に到着する時刻は、[917.54156669]
車両が顧客152に到着する時刻は、[919.77763467]
車両が顧客153に到着する時刻は、[930.54796429]
車両が顧客154に到着する時刻は、[935.93312909]
車両が顧客155に到着する時刻は、[939.53868037]
車両が顧客156に到着する時刻は、[942.53868037]
車両が顧客157に到着する時刻は、[947.53868037]
車両が顧客158に到着する時刻は、[954.74978292]
車両が顧客159に到着する時刻は、[962.5600326]
車両が顧客160に到着する時刻は、[972.60990822]
車両が顧客161に到着する時刻は、[976.21545949]
車両が顧客162に到着する時刻は、[981.6006243]
車両が顧客163に到着する時刻は、[985.84326499]
車両が顧客164に到着する時刻は、[991.67421688]
車両が顧客165に到着する時刻は、[1002.30436269]
車両が顧客166に到着する時刻は、[1009.37543051]
車両が顧客167に到着する時刻は、[1017.43768825]
車両が顧客168に到着する時刻は、[1022.53670777]
車両が顧客169に到着する時刻は、[1027.53670777]
車両が顧客170に到着する時刻は、[1033.6194703]
車両が顧客171に到着する時刻は、[1042.83901475]
車両が顧客172に到着する時刻は、[1045.07508273]
車両が顧客173に到着する時刻は、[1050.07508273]
車両が顧客174に到着する時刻は、[1054.07508273]
車両

車両が顧客481に到着する時刻は、[2867.03800702]
車両が顧客482に到着する時刻は、[2869.27407499]
車両が顧客483に到着する時刻は、[2874.27407499]
車両が顧客484に到着する時刻は、[2879.27407499]
車両が顧客485に到着する時刻は、[2881.51014297]
車両が顧客486に到着する時刻は、[2884.67242063]
車両が顧客487に到着する時刻は、[2893.61669254]
車両が顧客488に到着する時刻は、[2897.85933323]
車両が顧客489に到着する時刻は、[2898.85933323]
車両が顧客490に到着する時刻は、[2901.85933323]
車両が顧客491に到着する時刻は、[2904.09540121]
車両が顧客492に到着する時刻は、[2913.31494566]
車両が顧客493に到着する時刻は、[2914.72915923]
車両が顧客494に到着する時刻は、[2926.04286773]
車両が顧客495に到着する時刻は、[2935.47684886]
車両が顧客496に到着する時刻は、[2944.91082999]
車両が顧客497に到着する時刻は、[2946.32504355]
車両が顧客498に到着する時刻は、[2955.54458801]
車両が顧客499に到着する時刻は、[2964.14691328]
車両が顧客500に到着する時刻は、[2964.14691328]
車両が顧客501に到着する時刻は、[2969.97786517]
車両が顧客502に到着する時刻は、[2972.8062923]
車両が顧客503に到着する時刻は、[2981.29157367]
車両が顧客504に到着する時刻は、[2989.77685504]
車両が顧客505に到着する時刻は、[2999.21083618]
車両が顧客506に到着する時刻は、[3002.21083618]
車両が顧客507に到着する時刻は、[3006.3339418]
車両が顧客508に到着する時刻は、[3013.61405169]
車両が顧客509に到着する時刻は、[3019.69681422]
車両が顧客510に到着する時刻は、[3027.75907197]
車両が顧客511に到着す

車両が顧客734に到着する時刻は、[4173.18330982]
車両が顧客735に到着する時刻は、[4174.59752339]
車両が顧客736に到着する時刻は、[4181.30572732]
車両が顧客737に到着する時刻は、[4185.42883294]
車両が顧客738に到着する時刻は、[4186.42883294]
車両が顧客739に到着する時刻は、[4196.86913945]
車両が顧客740に到着する時刻は、[4199.86913945]
車両が顧客741に到着する時刻は、[4208.1153507]
車両が顧客742に到着する時刻は、[4210.94377783]
車両が顧客743に到着する時刻は、[4215.06688345]
車両が顧客744に到着する時刻は、[4224.50086459]
車両が顧客745に到着する時刻は、[4225.50086459]
車両が顧客746に到着する時刻は、[4228.32929171]
車両が顧客747に到着する時刻は、[4232.80142767]
車両が顧客748に到着する時刻は、[4242.02097212]
車両が顧客749に到着する時刻は、[4256.16310775]
車両が顧客750に到着する時刻は、[4258.99153487]
車両が顧客751に到着する時刻は、[4267.53553862]
車両が顧客752に到着する時刻は、[4273.36649051]
車両が顧客753に到着する時刻は、[4274.36649051]
車両が顧客754に到着する時刻は、[4280.36649051]
車両が顧客755に到着する時刻は、[4283.36649051]
車両が顧客756に到着する時刻は、[4290.07469444]
車両が顧客757に到着する時刻は、[4295.90564634]
車両が顧客758に到着する時刻は、[4295.90564634]
車両が顧客759に到着する時刻は、[4300.37778229]
車両が顧客760に到着する時刻は、[4308.92178604]
車両が顧客761に到着する時刻は、[4312.52733732]
車両が顧客762に到着する時刻は、[4319.59840513]
車両が顧客763に到着する時刻は、[4322.76068279]
車両が顧客764に到着

車両が顧客1007に到着する時刻は、[5709.95794669]
車両が顧客1008に到着する時刻は、[5719.17749115]
車両が顧客1009に到着する時刻は、[5726.24855896]
車両が顧客1010に到着する時刻は、[5733.52866885]
車両が顧客1011に到着する時刻は、[5737.52866885]
車両が顧客1012に到着する時刻は、[5742.91383366]
車両が顧客1013に到着する時刻は、[5745.74226078]
車両が顧客1014に到着する時刻は、[5750.21439674]
車両が顧客1015に到着する時刻は、[5757.42549929]
車両が顧客1016に到着する時刻は、[5760.58777695]
車両が顧客1017に到着する時刻は、[5765.0599129]
車両が顧客1018に到着する時刻は、[5769.0599129]
車両が顧客1019に到着する時刻は、[5774.0599129]
車両が顧客1020に到着する時刻は、[5780.14267543]
車両が顧客1021に到着する時刻は、[5783.74822671]
車両が顧客1022に到着する時刻は、[5794.04385685]
車両が顧客1023に到着する時刻は、[5802.2900681]
車両が顧客1024に到着する時刻は、[5808.12102]
車両が顧客1025に到着する時刻は、[5813.12102]
車両が顧客1026に到着する時刻は、[5822.9698778]
車両が顧客1027に到着する時刻は、[5825.9698778]
車両が顧客1028に到着する時刻は、[5834.03213555]
車両が顧客1029に到着する時刻は、[5835.44634911]
車両が顧客1030に到着する時刻は、[5841.10320336]
車両が顧客1031に到着する時刻は、[5852.76510715]
車両が顧客1032に到着する時刻は、[5855.59353427]
車両が顧客1033に到着する時刻は、[5856.59353427]
車両が顧客1034に到着する時刻は、[5858.82960225]
車両が顧客1035に到着する時刻は、[5869.26990876]
車両が顧客1036に到着する時刻は、[5874.36

車両が顧客1257に到着する時刻は、[7094.04601071]
車両が顧客1258に到着する時刻は、[7099.04601071]
車両が顧客1259に到着する時刻は、[7104.43117552]
車両が顧客1260に到着する時刻は、[7105.84538908]
車両が顧客1261に到着する時刻は、[7111.23055389]
車両が顧客1262に到着する時刻は、[7114.39283155]
車両が顧客1263に到着する時刻は、[7119.39283155]
車両が顧客1264に到着する時刻は、[7124.39283155]
車両が顧客1265に到着する時刻は、[7128.51593718]
車両が顧客1266に到着する時刻は、[7130.51593718]
車両が顧客1267に到着する時刻は、[7135.90110198]
車両が顧客1268に到着する時刻は、[7139.06337964]
車両が顧客1269に到着する時刻は、[7146.87362932]
車両が顧客1270に到着する時刻は、[7148.87362932]
車両が顧客1271に到着する時刻は、[7152.47918059]
車両が顧客1272に到着する時刻は、[7159.75929048]
車両が顧客1273に到着する時刻は、[7171.16104473]
車両が顧客1274に到着する時刻は、[7181.79119055]
車両が顧客1275に到着する時刻は、[7184.02725852]
車両が顧客1276に到着する時刻は、[7190.11002106]
車両が顧客1277に到着する時刻は、[7197.11002106]
車両が顧客1278に到着する時刻は、[7202.49518586]
車両が顧客1279に到着する時刻は、[7208.15204011]
車両が顧客1280に到着する時刻は、[7215.36314266]
車両が顧客1281に到着する時刻は、[7218.19156979]
車両が顧客1282に到着する時刻は、[7221.01999691]
車両が顧客1283に到着する時刻は、[7227.42312115]
車両が顧客1284に到着する時刻は、[7235.03889426]
車両が顧客1285に到着する時刻は、[7241.03889426]
車両が顧客1286に到着する

車両が顧客1527に到着する時刻は、[8614.09923624]
車両が顧客1528に到着する時刻は、[8615.5134498]
車両が顧客1529に到着する時刻は、[8616.5134498]
車両が顧客1530に到着する時刻は、[8621.89861461]
車両が顧客1531に到着する時刻は、[8625.50416588]
車両が顧客1532に到着する時刻は、[8627.74023386]
車両が顧客1533に到着する時刻は、[8630.90251152]
車両が顧客1534に到着する時刻は、[8642.9441061]
車両が顧客1535に到着する時刻は、[8654.34586035]
車両が顧客1536に到着する時刻は、[8656.58192833]
車両が顧客1537に到着する時刻は、[8659.58192833]
車両が顧客1538に到着する時刻は、[8666.29013226]
車両が顧客1539に到着する時刻は、[8672.29013226]
車両が顧客1540に到着する時刻は、[8682.13899006]
車両が顧客1541に到着する時刻は、[8694.86691212]
車両が顧客1542に到着する時刻は、[8702.48268523]
車両が顧客1543に到着する時刻は、[8706.72532592]
車両が顧客1544に到着する時刻は、[8708.13953948]
車両が顧客1545に到着する時刻は、[8712.38218017]
車両が顧客1546に到着する時刻は、[8714.61824814]
車両が顧客1547に到着する時刻は、[8719.61824814]
車両が顧客1548に到着する時刻は、[8730.24839396]
車両が顧客1549に到着する時刻は、[8740.29826958]
車両が顧客1550に到着する時刻は、[8747.29826958]
車両が顧客1551に到着する時刻は、[8753.70139382]
車両が顧客1552に到着する時刻は、[8761.51164349]
車両が顧客1553に到着する時刻は、[8772.1417893]
車両が顧客1554に到着する時刻は、[8780.68579305]
車両が顧客1555に到着する時刻は、[8784.29134433]
車両が顧客1556に到着する時刻は、

車両が顧客1775に到着する時刻は、[10086.04844272]
車両が顧客1776に到着する時刻は、[10091.87939461]
車両が顧客1777に到着する時刻は、[10093.29360818]
車両が顧客1778に到着する時刻は、[10095.29360818]
車両が顧客1779に到着する時刻は、[10101.6181635]
車両が顧客1780に到着する時刻は、[10106.6181635]
車両が顧客1781に到着する時刻は、[10115.83770795]
車両が顧客1782に到着する時刻は、[10116.83770795]
車両が顧客1783に到着する時刻は、[10122.83770795]
車両が顧客1784に到着する時刻は、[10130.8999657]
車両が顧客1785に到着する時刻は、[10138.96222345]
車両が顧客1786に到着する時刻は、[10146.57799656]
車両が顧客1787に到着する時刻は、[10153.85810645]
車両が顧客1788に到着する時刻は、[10159.68905834]
車両が顧客1789に到着する時刻は、[10161.1032719]
車両が顧客1790に到着する時刻は、[10165.22637753]
車両が顧客1791に到着する時刻は、[10166.22637753]
車両が顧客1792に到着する時刻は、[10171.32539704]
車両が顧客1793に到着する時刻は、[10177.15634894]
車両が顧客1794に到着する時刻は、[10186.64318192]
車両が顧客1795に到着する時刻は、[10192.72594445]
車両が顧客1796に到着する時刻は、[10196.84905007]
車両が顧客1797に到着する時刻は、[10204.65929975]
車両が顧客1798に到着する時刻は、[10213.65929975]
車両が顧客1799に到着する時刻は、[10221.905511]
車両が顧客1800に到着する時刻は、[10227.7364629]
車両が顧客1801に到着する時刻は、[10232.20859885]
車両が顧客1802に到着する時刻は、[10242.20859885]
車両が顧客1803に到着する時刻は、[10243.20

車両が顧客2039に到着する時刻は、[11597.969882]
車両が顧客2040に到着する時刻は、[11605.04094982]
車両が顧客2041に到着する時刻は、[11613.28716107]
車両が顧客2042に到着する時刻は、[11619.995365]
車両が顧客2043に到着する時刻は、[11621.40957856]
車両が顧客2044に到着する時刻は、[11627.24053046]
車両が顧客2045に到着する時刻は、[11635.05078013]
車両が顧客2046に到着する時刻は、[11639.17388576]
車両が顧客2047に到着する時刻は、[11642.77943703]
車両が顧客2048に到着する時刻は、[11645.01550501]
車両が顧客2049に到着する時刻は、[11647.25157299]
車両が顧客2050に到着する時刻は、[11650.85712426]
車両が顧客2051に到着する時刻は、[11656.93988679]
車両が顧客2052に到着する時刻は、[11662.03890631]
車両が顧客2053に到着する時刻は、[11671.47288744]
車両が顧客2054に到着する時刻は、[11678.75299733]
車両が顧客2055に到着する時刻は、[11684.13816214]
車両が顧客2056に到着する時刻は、[11687.3004398]
車両が顧客2057に到着する時刻は、[11692.3004398]
車両が顧客2058に到着する時刻は、[11697.6856046]
車両が顧客2059に到着する時刻は、[11702.15774056]
車両が顧客2060に到着する時刻は、[11706.40038125]
車両が顧客2061に到着する時刻は、[11715.00270651]
車両が顧客2062に到着する時刻は、[11717.23877449]
車両が顧客2063に到着する時刻は、[11720.40105215]
車両が顧客2064に到着する時刻は、[11728.4633099]
車両が顧客2065に到着する時刻は、[11735.4633099]
車両が顧客2066に到着する時刻は、[11736.87752346]
車両が顧客2067に到着する時刻は、[11742.2626

車両が顧客2284に到着する時刻は、[13002.71625528]
車両が顧客2285に到着する時刻は、[13006.32180656]
車両が顧客2286に到着する時刻は、[13014.80708793]
車両が顧客2287に到着する時刻は、[13020.63803983]
車両が顧客2288に到着する時刻は、[13022.63803983]
車両が顧客2289に到着する時刻は、[13024.8741078]
車両が顧客2290に到着する時刻は、[13026.28832137]
車両が顧客2291に到着する時刻は、[13029.89387264]
車両が顧客2292に到着する時刻は、[13035.27903745]
車両が顧客2293に到着する時刻は、[13044.49858191]
車両が顧客2294に到着する時刻は、[13046.73464988]
車両が顧客2295に到着する時刻は、[13056.16863102]
車両が顧客2296に到着する時刻は、[13066.01748882]
車両が顧客2297に到着する時刻は、[13072.42061306]
車両が顧客2298に到着する時刻は、[13078.82373729]
車両が顧客2299に到着する時刻は、[13085.53194123]
車両が顧客2300に到着する時刻は、[13086.53194123]
車両が顧客2301に到着する時刻は、[13087.53194123]
車両が顧客2302に到着する時刻は、[13090.53194123]
車両が顧客2303に到着する時刻は、[13094.77458191]
車両が顧客2304に到着する時刻は、[13096.77458191]
車両が顧客2305に到着する時刻は、[13104.83683966]
車両が顧客2306に到着する時刻は、[13111.16139498]
車両が顧客2307に到着する時刻は、[13117.4859503]
車両が顧客2308に到着する時刻は、[13118.90016386]
車両が顧客2309に到着する時刻は、[13124.90016386]
車両が顧客2310に到着する時刻は、[13130.98292639]
車両が顧客2311に到着する時刻は、[13139.22913765]
車両が顧客2312に到着する時刻は、[131

車両が顧客2520に到着する時刻は、[14305.79439395]
車両が顧客2521に到着する時刻は、[14309.91749957]
車両が顧客2522に到着する時刻は、[14312.15356755]
車両が顧客2523に到着する時刻は、[14317.15356755]
車両が顧客2524に到着する時刻は、[14321.39620824]
車両が顧客2525に到着する時刻は、[14328.60731079]
車両が顧客2526に到着する時刻は、[14338.50680573]
車両が顧客2527に到着する時刻は、[14341.66908339]
車両が顧客2528に到着する時刻は、[14349.73134113]
車両が顧客2529に到着する時刻は、[14361.13309538]
車両が顧客2530に到着する時刻は、[14363.36916336]
車両が顧客2531に到着する時刻は、[14363.36916336]
車両が顧客2532に到着する時刻は、[14371.97148863]
車両が顧客2533に到着する時刻は、[14380.21769988]
車両が顧客2534に到着する時刻は、[14381.21769988]
車両が顧客2535に到着する時刻は、[14385.34080551]
車両が顧客2536に到着する時刻は、[14392.95657861]
車両が顧客2537に到着する時刻は、[14400.16768116]
車両が顧客2538に到着する時刻は、[14406.49223648]
車両が顧客2539に到着する時刻は、[14417.30889031]
車両が顧客2540に到着する時刻は、[14423.30889031]
車両が顧客2541に到着する時刻は、[14430.51999286]
車両が顧客2542に到着する時刻は、[14435.61901237]
車両が顧客2543に到着する時刻は、[14442.69008019]
車両が顧客2544に到着する時刻は、[14450.30585329]
車両が顧客2545に到着する時刻は、[14455.30585329]
車両が顧客2546に到着する時刻は、[14461.38861582]
車両が顧客2547に到着する時刻は、[14472.56895571]
車両が顧客2548に到着する時刻は、[1

車両が顧客2833に到着する時刻は、[16142.87338191]
車両が顧客2834に到着する時刻は、[16148.25854672]
車両が顧客2835に到着する時刻は、[16155.53865661]
車両が顧客2836に到着する時刻は、[16165.58853223]
車両が顧客2837に到着する時刻は、[16174.80807669]
車両が顧客2838に到着する時刻は、[16178.41362796]
車両が顧客2839に到着する時刻は、[16184.49639049]
車両が顧客2840に到着する時刻は、[16193.04039424]
車両が顧客2841に到着する時刻は、[16203.04039424]
車両が顧客2842に到着する時刻は、[16212.52722722]
車両が顧客2843に到着する時刻は、[16219.73832977]
車両が顧客2844に到着する時刻は、[16226.06288509]
車両が顧客2845に到着する時刻は、[16234.06288509]
車両が顧客2846に到着する時刻は、[16238.18599071]
車両が顧客2847に到着する時刻は、[16238.18599071]
車両が顧客2848に到着する時刻は、[16244.18599071]
車両が顧客2849に到着する時刻は、[16248.4286314]
車両が顧客2850に到着する時刻は、[16252.55173703]
車両が顧客2851に到着する時刻は、[16259.76283958]
車両が顧客2852に到着する時刻は、[16268.30684332]
車両が顧客2853に到着する時刻は、[16275.30684332]
車両が顧客2854に到着する時刻は、[16281.38960585]
車両が顧客2855に到着する時刻は、[16286.77477066]
車両が顧客2856に到着する時刻は、[16290.77477066]
車両が顧客2857に到着する時刻は、[16294.38032194]
車両が顧客2858に到着する時刻は、[16295.7945355]
車両が顧客2859に到着する時刻は、[16303.85679325]
車両が顧客2860に到着する時刻は、[16310.85679325]
車両が顧客2861に到着する時刻は、[163

車両が顧客3078に到着する時刻は、[17530.64991091]
車両が顧客3079に到着する時刻は、[17534.77301654]
車両が顧客3080に到着する時刻は、[17543.71728845]
車両が顧客3081に到着する時刻は、[17552.93683291]
車両が顧客3082に到着する時刻は、[17554.35104647]
車両が顧客3083に到着する時刻は、[17563.57059093]
車両が顧客3084に到着する時刻は、[17567.69369655]
車両が顧客3085に到着する時刻は、[17571.29924783]
車両が顧客3086に到着する時刻は、[17578.00745176]
車両が顧客3087に到着する時刻は、[17585.62322487]
車両が顧客3088に到着する時刻は、[17594.22555013]
車両が顧客3089に到着する時刻は、[17597.05397726]
車両が顧客3090に到着する時刻は、[17603.45710149]
車両が顧客3091に到着する時刻は、[17612.67664595]
車両が顧客3092に到着する時刻は、[17616.28219723]
車両が顧客3093に到着する時刻は、[17617.28219723]
車両が顧客3094に到着する時刻は、[17622.66736203]
車両が顧客3095に到着する時刻は、[17625.49578916]
車両が顧客3096に到着する時刻は、[17629.61889479]
車両が顧客3097に到着する時刻は、[17640.2490406]
車両が顧客3098に到着する時刻は、[17650.2490406]
車両が顧客3099に到着する時刻は、[17654.37214622]
車両が顧客3100に到着する時刻は、[17657.53442388]
車両が顧客3101に到着する時刻は、[17662.00655984]
車両が顧客3102に到着する時刻は、[17670.95083175]
車両が顧客3103に到着する時刻は、[17672.36504531]
車両が顧客3104に到着する時刻は、[17677.46406482]
車両が顧客3105に到着する時刻は、[17681.58717045]
車両が顧客3106に到着する時刻は、[176

車両が顧客3330に到着する時刻は、[18960.90268705]
車両が顧客3331に到着する時刻は、[18967.30581129]
車両が顧客3332に到着する時刻は、[18972.30581129]
車両が顧客3333に到着する時刻は、[18977.30581129]
車両が顧客3334に到着する時刻は、[18981.42891692]
車両が顧客3335に到着する時刻は、[18989.23916659]
車両が顧客3336に到着する時刻は、[18991.23916659]
車両が顧客3337に到着する時刻は、[18999.30142434]
車両が顧客3338に到着する時刻は、[19007.36368209]
車両が顧客3339に到着する時刻は、[19009.59975007]
車両が顧客3340に到着する時刻は、[19014.98491487]
車両が顧客3341に到着する時刻は、[19018.14719253]
車両が顧客3342に到着する時刻は、[19019.5614061]
車両が顧客3343に到着する時刻は、[19023.16695737]
車両が顧客3344に到着する時刻は、[19025.40302535]
車両が顧客3345に到着する時刻は、[19028.56530301]
車両が顧客3346に到着する時刻は、[19030.80137099]
車両が顧客3347に到着する時刻は、[19031.80137099]
車両が顧客3348に到着する時刻は、[19040.7456429]
車両が顧客3349に到着する時刻は、[19046.7456429]
車両が顧客3350に到着する時刻は、[19057.18594941]
車両が顧客3351に到着する時刻は、[19062.57111421]
車両が顧客3352に到着する時刻は、[19071.17343948]
車両が顧客3353に到着する時刻は、[19072.17343948]
車両が顧客3354に到着する時刻は、[19082.9437691]
車両が顧客3355に到着する時刻は、[19087.9437691]
車両が顧客3356に到着する時刻は、[19095.75401877]
車両が顧客3357に到着する時刻は、[19100.22615473]
車両が顧客3358に到着する時刻は、[19104.

車両が顧客3609に到着する時刻は、[20477.24085791]
車両が顧客3610に到着する時刻は、[20488.64261216]
車両が顧客3611に到着する時刻は、[20496.70486991]
車両が顧客3612に到着する時刻は、[20499.70486991]
車両が顧客3613に到着する時刻は、[20501.70486991]
車両が顧客3614に到着する時刻は、[20508.91597246]
車両が顧客3615に到着する時刻は、[20513.03907809]
車両が顧客3616に到着する時刻は、[20515.86750521]
車両が顧客3617に到着する時刻は、[20519.47305649]
車両が顧客3618に到着する時刻は、[20523.59616211]
車両が顧客3619に到着する時刻は、[20532.65154725]
車両が顧客3620に到着する時刻は、[20542.08552838]
車両が顧客3621に到着する時刻は、[20548.4100837]
車両が顧客3622に到着する時刻は、[20552.65272439]
車両が顧客3623に到着する時刻は、[20555.48115151]
車両が顧客3624に到着する時刻は、[20556.48115151]
車両が顧客3625に到着する時刻は、[20559.64342917]
車両が顧客3626に到着する時刻は、[20561.87949715]
車両が顧客3627に到着する時刻は、[20561.87949715]
車両が顧客3628に到着する時刻は、[20571.36633013]
車両が顧客3629に到着する時刻は、[20575.48943576]
車両が顧客3630に到着する時刻は、[20581.14629001]
車両が顧客3631に到着する時刻は、[20586.9772419]
車両が顧客3632に到着する時刻は、[20592.9772419]
車両が顧客3633に到着する時刻は、[20596.13951956]
車両が顧客3634に到着する時刻は、[20600.13951956]
車両が顧客3635に到着する時刻は、[20608.20177731]
車両が顧客3636に到着する時刻は、[20615.81755042]
車両が顧客3637に到着する時刻は、[2062

車両が顧客3883に到着する時刻は、[22014.39187256]
車両が顧客3884に到着する時刻は、[22015.39187256]
車両が顧客3885に到着する時刻は、[22023.63808381]
車両が顧客3886に到着する時刻は、[22031.44833348]
車両が顧客3887に到着する時刻は、[22036.44833348]
車両が顧客3888に到着する時刻は、[22042.27928538]
車両が顧客3889に到着する時刻は、[22046.52192606]
車両が顧客3890に到着する時刻は、[22049.35035319]
車両が顧客3891に到着する時刻は、[22056.9661263]
車両が顧客3892に到着する時刻は、[22067.26175644]
車両が顧客3893に到着する時刻は、[22073.58631176]
車両が顧客3894に到着する時刻は、[22080.86642165]
車両が顧客3895に到着する時刻は、[22085.86642165]
車両が顧客3896に到着する時刻は、[22090.86642165]
車両が顧客3897に到着する時刻は、[22099.81069356]
車両が顧客3898に到着する時刻は、[22107.62094323]
車両が顧客3899に到着する時刻は、[22113.62094323]
車両が顧客3900に到着する時刻は、[22121.43119291]
車両が顧客3901に到着する時刻は、[22131.48106853]
車両が顧客3902に到着する時刻は、[22138.48106853]
車両が顧客3903に到着する時刻は、[22140.48106853]
車両が顧客3904に到着する時刻は、[22151.88282278]
車両が顧客3905に到着する時刻は、[22160.12903403]
車両が顧客3906に到着する時刻は、[22167.34013658]
車両が顧客3907に到着する時刻は、[22176.39552172]
車両が顧客3908に到着する時刻は、[22183.39552172]
車両が顧客3909に到着する時刻は、[22188.49454123]
車両が顧客3910に到着する時刻は、[22194.15139548]
車両が顧客3911に到着する時刻は、[22

車両が顧客4156に到着する時刻は、[23592.36553368]
車両が顧客4157に到着する時刻は、[23599.64564357]
車両が顧客4158に到着する時刻は、[23607.64564357]
車両が顧客4159に到着する時刻は、[23608.64564357]
車両が顧客4160に到着する時刻は、[23616.45589325]
車両が顧客4161に到着する時刻は、[23621.84105806]
車両が顧客4162に到着する時刻は、[23626.94007757]
車両が顧客4163に到着する時刻は、[23636.15962203]
車両が顧客4164に到着する時刻は、[23641.54478683]
車両が顧客4165に到着する時刻は、[23646.64380635]
車両が顧客4166に到着する時刻は、[23650.24935762]
車両が顧客4167に到着する時刻は、[23660.14885256]
車両が顧客4168に到着する時刻は、[23670.14885256]
車両が顧客4169に到着する時刻は、[23680.34689159]
車両が顧客4170に到着する時刻は、[23683.17531871]
車両が顧客4171に到着する時刻は、[23687.29842434]
車両が顧客4172に到着する時刻は、[23697.14728214]
車両が顧客4173に到着する時刻は、[23701.27038776]
車両が顧客4174に到着する時刻は、[23705.51302845]
車両が顧客4175に到着する時刻は、[23712.58409626]
車両が顧客4176に到着する時刻は、[23715.74637392]
車両が顧客4177に到着する時刻は、[23717.16058749]
車両が顧客4178に到着する時刻は、[23727.16058749]
車両が顧客4179に到着する時刻は、[23737.16058749]
車両が顧客4180に到着する時刻は、[23739.39665546]
車両が顧客4181に到着する時刻は、[23743.00220674]
車両が顧客4182に到着する時刻は、[23747.12531236]
車両が顧客4183に到着する時刻は、[23753.5284366]
車両が顧客4184に到着する時刻は、[23

車両が顧客4419に到着する時刻は、[25077.73111149]
車両が顧客4420に到着する時刻は、[25082.73111149]
車両が顧客4421に到着する時刻は、[25087.20324744]
車両が顧客4422に到着する時刻は、[25090.3655251]
車両が顧客4423に到着する時刻は、[25096.02237935]
車両が顧客4424に到着する時刻は、[25098.85080648]
車両が顧客4425に到着する時刻は、[25102.9739121]
車両が顧客4426に到着する時刻は、[25108.07293162]
車両が顧客4427に到着する時刻は、[25110.3089996]
車両が顧客4428に到着する時刻は、[25118.37125734]
車両が顧客4429に到着する時刻は、[25127.80523848]
車両が顧客4430に到着する時刻は、[25131.80523848]
車両が顧客4431に到着する時刻は、[25134.96751614]
車両が顧客4432に到着する時刻は、[25136.96751614]
車両が顧客4433に到着する時刻は、[25141.21015682]
車両が顧客4434に到着する時刻は、[25151.26003244]
車両が顧客4435に到着する時刻は、[25160.4795769]
車両が顧客4436に到着する時刻は、[25167.75968679]
車両が顧客4437に到着する時刻は、[25170.92196445]
車両が顧客4438に到着する時刻は、[25178.53773756]
車両が顧客4439に到着する時刻は、[25182.78037824]
車両が顧客4440に到着する時刻は、[25192.21435938]
車両が顧客4441に到着する時刻は、[25199.49446926]
車両が顧客4442に到着する時刻は、[25202.49446926]
車両が顧客4443に到着する時刻は、[25203.90868283]
車両が顧客4444に到着する時刻は、[25206.90868283]
車両が顧客4445に到着する時刻は、[25218.57058662]
車両が顧客4446に到着する時刻は、[25226.38083629]
車両が顧客4447に到着する時刻は、[25230

車両が顧客4665に到着する時刻は、[26515.9295777]
車両が顧客4666に到着する時刻は、[26521.9295777]
車両が顧客4667に到着する時刻は、[26521.9295777]
車両が顧客4668に到着する時刻は、[26532.55972351]
車両が顧客4669に到着する時刻は、[26541.77926797]
車両が顧客4670に到着する時刻は、[26544.01533595]
車両が顧客4671に到着する時刻は、[26554.01533595]
車両が顧客4672に到着する時刻は、[26564.45564245]
車両が顧客4673に到着する時刻は、[26568.06119373]
車両が顧客4674に到着する時刻は、[26569.47540729]
車両が顧客4675に到着する時刻は、[26574.57442681]
車両が顧客4676に到着する時刻は、[26580.65718934]
車両が顧客4677に到着する時刻は、[26591.47384316]
車両が顧客4678に到着する時刻は、[26596.85900797]
車両が顧客4679に到着する時刻は、[26601.95802748]
車両が顧客4680に到着する時刻は、[26606.95802748]
車両が顧客4681に到着する時刻は、[26608.37224105]
車両が顧客4682に到着する時刻は、[26613.47126056]
車両が顧客4683に到着する時刻は、[26615.70732854]
車両が顧客4684に到着する時刻は、[26615.70732854]
車両が顧客4685に到着する時刻は、[26624.76271367]
車両が顧客4686に到着する時刻は、[26626.76271367]
車両が顧客4687に到着する時刻は、[26634.82497142]
車両が顧客4688に到着する時刻は、[26638.94807705]
車両が顧客4689に到着する時刻は、[26644.77902894]
車両が顧客4690に到着する時刻は、[26651.99013149]
車両が顧客4691に到着する時刻は、[26659.06119931]
車両が顧客4692に到着する時刻は、[26660.47541287]
車両が顧客4693に到着する時刻は、[2666

車両が顧客4914に到着する時刻は、[27923.38503887]
車両が顧客4915に到着する時刻は、[27932.32931078]
車両が顧客4916に到着する時刻は、[27941.27358269]
車両が顧客4917に到着する時刻は、[27950.49312715]
車両が顧客4918に到着する時刻は、[27960.54300277]
車両が顧客4919に到着する時刻は、[27965.64202229]
車両が顧客4920に到着する時刻は、[27972.92213217]
車両が顧客4921に到着する時刻は、[27979.00489471]
車両が顧客4922に到着する時刻は、[27989.44520121]
車両が顧客4923に到着する時刻は、[27991.68126919]
車両が顧客4924に到着する時刻は、[27996.68126919]
車両が顧客4925に到着する時刻は、[28004.74352694]
車両が顧客4926に到着する時刻は、[28009.21566289]
車両が顧客4927に到着する時刻は、[28019.6559694]
車両が顧客4928に到着する時刻は、[28024.6559694]
車両が顧客4929に到着する時刻は、[28029.6559694]
車両が顧客4930に到着する時刻は、[28033.6559694]
車両が顧客4931に到着する時刻は、[28035.89203738]
車両が顧客4932に到着する時刻は、[28043.50781049]
車両が顧客4933に到着する時刻は、[28049.33876238]
車両が顧客4934に到着する時刻は、[28050.75297594]
車両が顧客4935に到着する時刻は、[28062.1547302]
車両が顧客4936に到着する時刻は、[28067.25374971]
車両が顧客4937に到着する時刻は、[28074.86952281]
車両が顧客4938に到着する時刻は、[28083.41352656]
車両が顧客4939に到着する時刻は、[28090.69363645]
車両が顧客4940に到着する時刻は、[28097.76470426]
車両が顧客4941に到着する時刻は、[28105.38047737]
車両が顧客4942に到着する時刻は、[28112.

車両が顧客5166に到着する時刻は、[29394.10221725]
車両が顧客5167に到着する時刻は、[29397.70776852]
車両が顧客5168に到着する時刻は、[29405.5180182]
車両が顧客5169に到着する時刻は、[29410.61703771]
車両が顧客5170に到着する時刻は、[29416.44798961]
車両が顧客5171に到着する時刻は、[29421.44798961]
車両が顧客5172に到着する時刻は、[29430.93482259]
車両が顧客5173に到着する時刻は、[29436.3199874]
車両が顧客5174に到着する時刻は、[29443.02819133]
車両が顧客5175に到着する時刻は、[29451.97246324]
車両が顧客5176に到着する時刻は、[29454.20853122]
車両が顧客5177に到着する時刻は、[29457.81408249]
車両が顧客5178に到着する時刻は、[29460.97636015]
車両が顧客5179に到着する時刻は、[29467.05912268]
車両が顧客5180に到着する時刻は、[29474.67489579]
車両が顧客5181に到着する時刻は、[29484.57439073]
車両が顧客5182に到着する時刻は、[29488.69749635]
車両が顧客5183に到着する時刻は、[29495.02205167]
車両が顧客5184に到着する時刻は、[29501.1048142]
車両が顧客5185に到着する時刻は、[29511.1048142]
車両が顧客5186に到着する時刻は、[29520.32435866]
車両が顧客5187に到着する時刻は、[29530.2238536]
車両が顧客5188に到着する時刻は、[29532.2238536]
車両が顧客5189に到着する時刻は、[29537.2238536]
車両が顧客5190に到着する時刻は、[29544.43495615]
車両が顧客5191に到着する時刻は、[29553.92178913]
車両が顧客5192に到着する時刻は、[29560.99285694]
車両が顧客5193に到着する時刻は、[29563.22892492]
車両が顧客5194に到着する時刻は、[29565.22

車両が顧客5406に到着する時刻は、[30822.1779338]
車両が顧客5407に到着する時刻は、[30827.1779338]
車両が顧客5408に到着する時刻は、[30830.78348507]
車両が顧客5409に到着する時刻は、[30835.02612576]
車両が顧客5410に到着する時刻は、[30841.02612576]
車両が顧客5411に到着する時刻は、[30847.42925]
車両が顧客5412に到着する時刻は、[30858.7429585]
車両が顧客5413に到着する時刻は、[30865.81402631]
車両が顧客5414に到着する時刻は、[30876.44417212]
車両が顧客5415に到着する時刻は、[30877.44417212]
車両が顧客5416に到着する時刻は、[30884.51523993]
車両が顧客5417に到着する時刻は、[30888.12079121]
車両が顧客5418に到着する時刻は、[30895.12079121]
車両が顧客5419に到着する時刻は、[30901.52391545]
車両が顧客5420に到着する時刻は、[30909.7701267]
車両が顧客5421に到着する時刻は、[30912.00619467]
車両が顧客5422に到着する時刻は、[30915.16847233]
車両が顧客5423に到着する時刻は、[30919.64060829]
車両が顧客5424に到着する時刻は、[30930.2707541]
車両が顧客5425に到着する時刻は、[30933.2707541]
車両が顧客5426に到着する時刻は、[30938.65591891]
車両が顧客5427に到着する時刻は、[30938.65591891]
車両が顧客5428に到着する時刻は、[30941.48434603]
車両が顧客5429に到着する時刻は、[30950.02834978]
車両が顧客5430に到着する時刻は、[30952.26441776]
車両が顧客5431に到着する時刻は、[30959.47552031]
車両が顧客5432に到着する時刻は、[30970.24584992]
車両が顧客5433に到着する時刻は、[30971.24584992]
車両が顧客5434に到着する時刻は、[30981.2458

車両が顧客5647に到着する時刻は、[32211.97915619]
車両が顧客5648に到着する時刻は、[32216.97915619]
車両が顧客5649に到着する時刻は、[32222.81010808]
車両が顧客5650に到着する時刻は、[32229.81010808]
車両が顧客5651に到着する時刻は、[32237.87236583]
車両が顧客5652に到着する時刻は、[32244.27549007]
車両が顧客5653に到着する時刻は、[32246.51155805]
車両が顧客5654に到着する時刻は、[32256.95186456]
車両が顧客5655に到着する時刻は、[32260.11414222]
車両が顧客5656に到着する時刻は、[32263.27641988]
車両が顧客5657に到着する時刻は、[32273.27641988]
車両が顧客5658に到着する時刻は、[32277.27641988]
車両が顧客5659に到着する時刻は、[32279.27641988]
車両が顧客5660に到着する時刻は、[32287.82042362]
車両が顧客5661に到着する時刻は、[32291.82042362]
車両が顧客5662に到着する時刻は、[32292.82042362]
車両が顧客5663に到着する時刻は、[32300.03152617]
車両が顧客5664に到着する時刻は、[32307.31163606]
車両が顧客5665に到着する時刻は、[32314.59174595]
車両が顧客5666に到着する時刻は、[32318.71485158]
車両が顧客5667に到着する時刻は、[32329.48518119]
車両が顧客5668に到着する時刻は、[32330.89939475]
車両が顧客5669に到着する時刻は、[32341.09743378]
車両が顧客5670に到着する時刻は、[32347.50055802]
車両が顧客5671に到着する時刻は、[32349.736626]
車両が顧客5672に到着する時刻は、[32357.79888374]
車両が顧客5673に到着する時刻は、[32366.28416512]
車両が顧客5674に到着する時刻は、[32374.82816886]
車両が顧客5675に到着する時刻は、[323

車両が顧客5920に到着する時刻は、[33732.24694981]
車両が顧客5921に到着する時刻は、[33733.66116337]
車両が顧客5922に到着する時刻は、[33743.14799635]
車両が顧客5923に到着する時刻は、[33746.31027401]
車両が顧客5924に到着する時刻は、[33755.797107]
車両が顧客5925に到着する時刻は、[33759.92021262]
車両が顧客5926に到着する時刻は、[33762.1562806]
車両が顧客5927に到着する時刻は、[33768.55940484]
車両が顧客5928に到着する時刻は、[33770.55940484]
車両が顧客5929に到着する時刻は、[33770.55940484]
車両が顧客5930に到着する時刻は、[33780.04623782]
車両が顧客5931に到着する時刻は、[33788.10849556]
車両が顧客5932に到着する時刻は、[33796.65249931]
車両が顧客5933に到着する時刻は、[33805.19650306]
車両が顧客5934に到着する時刻は、[33807.43257103]
車両が顧客5935に到着する時刻は、[33813.26352293]
車両が顧客5936に到着する時刻は、[33818.92037718]
車両が顧客5937に到着する時刻は、[33825.99144499]
車両が顧客5938に到着する時刻は、[33833.0625128]
車両が顧客5939に到着する時刻は、[33834.47672636]
車両が顧客5940に到着する時刻は、[33843.69627082]
車両が顧客5941に到着する時刻は、[33850.97638071]
車両が顧客5942に到着する時刻は、[33854.58193199]
車両が顧客5943に到着する時刻は、[33859.58193199]
車両が顧客5944に到着する時刻は、[33862.74420965]
車両が顧客5945に到着する時刻は、[33867.74420965]
車両が顧客5946に到着する時刻は、[33873.82697218]
車両が顧客5947に到着する時刻は、[33877.43252345]
車両が顧客5948に到着する時刻は、[33884

車両が顧客6170に到着する時刻は、[35113.72601478]
車両が顧客6171に到着する時刻は、[35115.96208276]
車両が顧客6172に到着する時刻は、[35120.96208276]
車両が顧客6173に到着する時刻は、[35126.61893701]
車両が顧客6174に到着する時刻は、[35130.22448828]
車両が顧客6175に到着する時刻は、[35139.44403274]
車両が顧客6176に到着する時刻は、[35143.04958402]
車両が顧客6177に到着する時刻は、[35151.99385593]
車両が顧客6178に到着する時刻は、[35160.93812784]
車両が顧客6179に到着する時刻は、[35168.21823773]
車両が顧客6180に到着する時刻は、[35177.27362286]
車両が顧客6181に到着する時刻は、[35180.10204999]
車両が顧客6182に到着する時刻は、[35182.10204999]
車両が顧客6183に到着する時刻は、[35188.81025392]
車両が顧客6184に到着する時刻は、[35191.81025392]
車両が顧客6185に到着する時刻は、[35194.97253158]
車両が顧客6186に到着する時刻は、[35197.80095871]
車両が顧客6187に到着する時刻は、[35207.02050316]
車両が顧客6188に到着する時刻は、[35208.43471673]
車両が顧客6189に到着する時刻は、[35217.37898864]
車両が顧客6190に到着する時刻は、[35227.42886426]
車両が顧客6191に到着する時刻は、[35230.42886426]
車両が顧客6192に到着する時刻は、[35241.24551808]
車両が顧客6193に到着する時刻は、[35250.67949922]
車両が顧客6194に到着する時刻は、[35257.38770315]
車両が顧客6195に到着する時刻は、[35260.54998081]
車両が顧客6196に到着する時刻は、[35265.54998081]
車両が顧客6197に到着する時刻は、[35271.63274334]
車両が顧客6198に到着する時刻は、[3

In [ ]:
for var in whole_x.getVars():
    print(var.varName, var.X)

In [ ]:
for constr in whole_x.getConstrs():
    print(constr.Pi)

## ②前半と後半をつなげるveb.
1. 適当なところで前後に分ける
1. 前半後半それぞれのPrimalを解く
1. 前半と後半それぞれのPrimalの最適解を、全体のDualに入れて解く
1. 全体のPrimalの最適解を得る

### 1. 適当なところで前後に分ける
- ひとまず半分くらいで分けることにする

In [13]:
threshold = len(tour)//2
#print(threshold)

former = tour[:threshold]
latter = tour[threshold:]
#print(f"巡回路全体は、{tour}")
print(f"前半は、{former}")
print(f"後半は、{latter}")

前半は、[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 

### 2. 前半後半それぞれのPrimalを解く

In [14]:
import numpy as np
# 係数行列、ベクトルを整える
A1x, A1p, A2x, A2p, A3x, A3p, b1, b2, b3, c1, c2 = [], [], [], [], [], [], [], [], [], [], []
## A1, A2, A3を定める
## b1, b2, b3を定める
for Ax_i, Ap_i, b_i in zip(Ax, Ap, b):
    if np.linalg.norm(Ax_i[threshold:], ord=2)==0.:
        A1x.append(Ax_i[:threshold])
        A1p.append(Ap_i[:threshold])
        b1.append(b_i)
    elif np.linalg.norm(Ax_i[:threshold], ord=2)==0.:
        A2x.append(Ax_i[threshold:])
        A2p.append(Ap_i[threshold:])
        b2.append(b_i)
    else:
        A3x.append(Ax_i)
        A3p.append(Ap_i)
        b3.append(b_i)
## c1, c2, c3を定める
c1 = c[:threshold]
c2 = c[threshold:]
## リストからnumpy arrayに変換
A1x = np.array(A1x)
A1p = np.array(A1p)
A2x = np.array(A2x)
A2p = np.array(A2p)
A3x = np.array(A3x)
A3p = np.array(A3p)
b1 = np.array(b1)
b2 = np.array(b2)
b3 = np.array(b3)
c1 = np.array(c1)
c2 = np.array(c2)
for i in range(1, 4):
    print(f"A{i}x : ", end="")
    print(eval("A"+str(i)+"x"))
    print(f"A{i}p : ", end="")
    print(eval("A"+str(i)+"p"))
    print(f"b{i} : ", end="")
    print(eval("b"+str(i)))
    if i <= 2:
        print(eval("c"+str(i)))

A1x : [[ 1 -1  0 ...  0  0  0]
 [ 0  1 -1 ...  0  0  0]
 [ 0  0  1 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  1  0]
 [ 0  0  0 ...  0  0 -1]
 [ 0  0  0 ...  0  0  1]]
A1p : [[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0 -1  0]
 [ 0  0  0 ...  0  0 -1]
 [ 0  0  0 ...  0  0 -1]]
b1 : [-6.08276253e+00 -3.60555128e+00 -5.83095189e+00 ...  1.10180000e+04
 -1.10190000e+04  1.10230000e+04]
[1 1 1 ... 1 1 1]
A2x : [[ 1 -1  0 ...  0  0  0]
 [ 0  1 -1 ...  0  0  0]
 [ 0  0  1 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  1  0]
 [ 0  0  0 ...  0  0 -1]
 [ 0  0  0 ...  0  0  1]]
A2p : [[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0 -1  0]
 [ 0  0  0 ...  0  0 -1]
 [ 0  0  0 ...  0  0 -1]]
b2 : [-1.00000000e+01 -6.70820393e+00 -8.06225775e+00 ...  2.20510000e+04
  0.00000000e+00  1.00000000e+03]
[1 1 1 ... 1 1 1]
A3x : [[0 0 0 ... 0 0 0]]
A3p : [[0 0 0 ... 0 0 0]]
b3 : [-8.06225775]


In [15]:
# Gurobiによって最適解を求める
former_x = solve_primal(A1x, A1p, b1, c1, instance_name+"former_x", len(former))
latter_x = solve_primal(A2x, A2p, b2, c2, instance_name+"latter_x", len(latter))

Gurobi Optimizer version 9.0.2 build v9.0.2rc0 (mac64)
Optimize a model with 9482 rows, 6322 columns and 18964 nonzeros
Model fingerprint: 0x79f6c9b9
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+04]
Presolve removed 6294 rows and 3136 columns
Presolve time: 0.05s
Presolved: 3188 rows, 3186 columns, 6376 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    1.0943210e+07   4.794063e+00   0.000000e+00      0s
    2980    1.0954124e+07   0.000000e+00   0.000000e+00      0s

Solved in 2980 iterations and 0.17 seconds
Optimal objective  1.095412389e+07
車両が顧客0に到着する時刻は、[0.]
車両が顧客1に到着する時刻は、[6.08276253]
車両が顧客2に到着する時刻は、[9.68831381]
車両が顧客3に到着する時刻は、[15.5192657]
車両が顧客4に到着する時刻は、[22.5192657]
車両が顧客5に到着する時刻は、[24.5192657]
車両が顧客6に到着する時刻は、[35.8329742]
車両が顧客7に到着する時刻は、[47.23472845]
車両が顧客8に到着する時刻は、[55.7787322]
車両が顧客9に到着する時刻は、[59.38428347]
車両が顧客10に到着する時刻は、[67.44654122]

車両が顧客237に到着する時刻は、[1390.26410443]
車両が顧客238に到着する時刻は、[1400.55973457]
車両が顧客239に到着する時刻は、[1409.99371571]
車両が顧客240に到着する時刻は、[1413.15599337]
車両が顧客241に到着する時刻は、[1417.15599337]
車両が顧客242に到着する時刻は、[1421.27909899]
車両が顧客243に到着する時刻は、[1426.27909899]
車両が顧客244に到着する時刻は、[1432.60365431]
車両が顧客245に到着する時刻は、[1438.92820963]
車両が顧客246に到着する時刻は、[1442.92820963]
車両が顧客247に到着する時刻は、[1447.92820963]
車両が顧客248に到着する時刻は、[1454.63641357]
車両が顧客249に到着する時刻は、[1466.29831736]
車両が顧客250に到着する時刻は、[1476.49635638]
車両が顧客251に到着する時刻は、[1481.88152119]
車両が顧客252に到着する時刻は、[1491.10106565]
車両が顧客253に到着する時刻は、[1497.50418988]
車両が顧客254に到着する時刻は、[1501.62729551]
車両が顧客255に到着する時刻は、[1511.67717113]
車両が顧客256に到着する時刻は、[1513.91323911]
車両が顧客257に到着する時刻は、[1516.74166623]
車両が顧客258に到着する時刻は、[1523.74166623]
車両が顧客259に到着する時刻は、[1529.12683104]
車両が顧客260に到着する時刻は、[1538.56081217]
車両が顧客261に到着する時刻は、[1549.33114179]
車両が顧客262に到着する時刻は、[1551.33114179]
車両が顧客263に到着する時刻は、[1555.57378247]
車両が顧客264に到着する時刻は、[1562.78488503]
車両が顧客265に到着する時刻は、[1568.86764756]
車両が顧客266に到着する時刻は、[1576.9299053]
車両が顧客267に到着

車両が顧客586に到着する時刻は、[3380.04267668]
車両が顧客587に到着する時刻は、[3387.85292636]
車両が顧客588に到着する時刻は、[3394.92399417]
車両が顧客589に到着する時刻は、[3395.92399417]
車両が顧客590に到着する時刻は、[3402.0067567]
車両が顧客591に到着する時刻は、[3411.0067567]
車両が顧客592に到着する時刻は、[3418.07782451]
車両が顧客593に到着する時刻は、[3427.51180564]
車両が顧客594に到着する時刻は、[3435.12757875]
車両が顧客595に到着する時刻は、[3438.12757875]
車両が顧客596に到着する時刻は、[3444.53070299]
車両が顧客597に到着する時刻は、[3450.18755724]
車両が顧客598に到着する時刻は、[3459.40710169]
車両が顧客599に到着する時刻は、[3462.23552882]
車両が顧客600に到着する時刻は、[3465.06395594]
車両が顧客601に到着する時刻は、[3471.14671847]
車両が顧客602に到着する時刻は、[3477.229481]
車両が顧客603に到着する時刻は、[3484.30054882]
車両が顧客604に到着する時刻は、[3492.84455256]
車両が顧客605に到着する時刻は、[3498.92731509]
車両が顧客606に到着する時刻は、[3504.3124799]
車両が顧客607に到着する時刻は、[3510.63703522]
車両が顧客608に到着する時刻は、[3521.07734173]
車両が顧客609に到着する時刻は、[3523.31340971]
車両が顧客610に到着する時刻は、[3524.72762327]
車両が顧客611に到着する時刻は、[3528.33317454]
車両が顧客612に到着する時刻は、[3538.62880468]
車両が顧客613に到着する時刻は、[3547.68418982]
車両が顧客614に到着する時刻は、[3550.51261695]
車両が顧客615に到着する時刻は、[3557.51261695]
車両が顧客616に到着する時刻

車両が顧客843に到着する時刻は、[4777.47861463]
車両が顧客844に到着する時刻は、[4783.56137716]
車両が顧客845に到着する時刻は、[4791.37162683]
車両が顧客846に到着する時刻は、[4798.65173672]
車両が顧客847に到着する時刻は、[4806.89794797]
車両が顧客848に到着する時刻は、[4813.96901579]
車両が顧客849に到着する時刻は、[4818.21165647]
車両が顧客850に到着する時刻は、[4821.81720775]
車両が顧客851に到着する時刻は、[4829.8794655]
車両が顧客852に到着する時刻は、[4831.29367906]
車両が顧客853に到着する時刻は、[4838.29367906]
車両が顧客854に到着する時刻は、[4841.45595672]
車両が顧客855に到着する時刻は、[4843.6920247]
車両が顧客856に到着する時刻は、[4849.6920247]
車両が顧客857に到着する時刻は、[4856.76309251]
車両が顧客858に到着する時刻は、[4863.83416032]
車両が顧客859に到着する時刻は、[4874.46430613]
車両が顧客860に到着する時刻は、[4881.17251007]
車両が顧客861に到着する時刻は、[4888.24357788]
車両が顧客862に到着する時刻は、[4892.48621856]
車両が顧客863に到着する時刻は、[4892.48621856]
車両が顧客864に到着する時刻は、[4895.64849622]
車両が顧客865に到着する時刻は、[4903.64849622]
車両が顧客866に到着する時刻は、[4912.86804068]
車両が顧客867に到着する時刻は、[4918.69899258]
車両が顧客868に到着する時刻は、[4927.24299632]
車両が顧客869に到着する時刻は、[4935.48920757]
車両が顧客870に到着する時刻は、[4941.32015947]
車両が顧客871に到着する時刻は、[4945.32015947]
車両が顧客872に到着する時刻は、[4949.56280016]
車両が顧客873に到着する

車両が顧客1249に到着する時刻は、[7054.43105225]
車両が顧客1250に到着する時刻は、[7062.04682536]
車両が顧客1251に到着する時刻は、[7065.04682536]
車両が顧客1252に到着する時刻は、[7067.28289334]
車両が顧客1253に到着する時刻は、[7072.38191285]
車両が顧客1254に到着する時刻は、[7079.45298066]
車両が顧客1255に到着する時刻は、[7082.61525832]
車両が顧客1256に到着する時刻は、[7091.21758359]
車両が顧客1257に到着する時刻は、[7094.04601071]
車両が顧客1258に到着する時刻は、[7099.04601071]
車両が顧客1259に到着する時刻は、[7104.43117552]
車両が顧客1260に到着する時刻は、[7105.84538908]
車両が顧客1261に到着する時刻は、[7111.23055389]
車両が顧客1262に到着する時刻は、[7114.39283155]
車両が顧客1263に到着する時刻は、[7119.39283155]
車両が顧客1264に到着する時刻は、[7124.39283155]
車両が顧客1265に到着する時刻は、[7128.51593718]
車両が顧客1266に到着する時刻は、[7130.51593718]
車両が顧客1267に到着する時刻は、[7135.90110198]
車両が顧客1268に到着する時刻は、[7139.06337964]
車両が顧客1269に到着する時刻は、[7146.87362932]
車両が顧客1270に到着する時刻は、[7148.87362932]
車両が顧客1271に到着する時刻は、[7152.47918059]
車両が顧客1272に到着する時刻は、[7159.75929048]
車両が顧客1273に到着する時刻は、[7171.16104473]
車両が顧客1274に到着する時刻は、[7181.79119055]
車両が顧客1275に到着する時刻は、[7184.02725852]
車両が顧客1276に到着する時刻は、[7190.11002106]
車両が顧客1277に到着する時刻は、[7197.11002106]
車両が顧客1278に到着する

車両が顧客1513に到着する時刻は、[8536.4564814]
車両が顧客1514に到着する時刻は、[8544.26673108]
車両が顧客1515に到着する時刻は、[8552.86905634]
車両が顧客1516に到着する時刻は、[8562.0886008]
車両が顧客1517に到着する時刻は、[8571.30814526]
車両が顧客1518に到着する時刻は、[8575.43125089]
車両が顧客1519に到着する時刻は、[8582.5023187]
車両が顧客1520に到着する時刻は、[8583.91653226]
車両が顧客1521に到着する時刻は、[8588.15917295]
車両が顧客1522に到着する時刻は、[8594.24193548]
車両が顧客1523に到着する時刻は、[8598.71407143]
車両が顧客1524に到着する時刻は、[8603.71407143]
車両が顧客1525に到着する時刻は、[8609.09923624]
車両が顧客1526に到着する時刻は、[8613.09923624]
車両が顧客1527に到着する時刻は、[8614.09923624]
車両が顧客1528に到着する時刻は、[8615.5134498]
車両が顧客1529に到着する時刻は、[8616.5134498]
車両が顧客1530に到着する時刻は、[8621.89861461]
車両が顧客1531に到着する時刻は、[8625.50416588]
車両が顧客1532に到着する時刻は、[8627.74023386]
車両が顧客1533に到着する時刻は、[8630.90251152]
車両が顧客1534に到着する時刻は、[8642.9441061]
車両が顧客1535に到着する時刻は、[8654.34586035]
車両が顧客1536に到着する時刻は、[8656.58192833]
車両が顧客1537に到着する時刻は、[8659.58192833]
車両が顧客1538に到着する時刻は、[8666.29013226]
車両が顧客1539に到着する時刻は、[8672.29013226]
車両が顧客1540に到着する時刻は、[8682.13899006]
車両が顧客1541に到着する時刻は、[8694.86691212]
車両が顧客1542に到着する時刻は、[8

車両が顧客1758に到着する時刻は、[9980.13089911]
車両が顧客1759に到着する時刻は、[9984.3735398]
車両が顧客1760に到着する時刻は、[9989.47255931]
車両が顧客1761に到着する時刻は、[9994.85772412]
車両が顧客1762に到着する時刻は、[10006.03806401]
車両が顧客1763に到着する時刻は、[10015.25760847]
車両が顧客1764に到着する時刻は、[10018.41988613]
車両が顧客1765に到着する時刻は、[10024.50264866]
車両が顧客1766に到着する時刻は、[10029.50264866]
車両が顧客1767に到着する時刻は、[10031.73871663]
車両が顧客1768に到着する時刻は、[10035.34426791]
車両が顧客1769に到着する時刻は、[10041.1752198]
車両が顧客1770に到着する時刻は、[10050.66205278]
車両が顧客1771に到着する時刻は、[10059.88159724]
車両が顧客1772に到着する時刻は、[10063.48714852]
車両が顧客1773に到着する時刻は、[10072.08947378]
車両が顧客1774に到着する時刻は、[10081.57630677]
車両が顧客1775に到着する時刻は、[10086.04844272]
車両が顧客1776に到着する時刻は、[10091.87939461]
車両が顧客1777に到着する時刻は、[10093.29360818]
車両が顧客1778に到着する時刻は、[10095.29360818]
車両が顧客1779に到着する時刻は、[10101.6181635]
車両が顧客1780に到着する時刻は、[10106.6181635]
車両が顧客1781に到着する時刻は、[10115.83770795]
車両が顧客1782に到着する時刻は、[10116.83770795]
車両が顧客1783に到着する時刻は、[10122.83770795]
車両が顧客1784に到着する時刻は、[10130.8999657]
車両が顧客1785に到着する時刻は、[10138.96222345]
車両が顧客1786に到着する時刻は、[10146.5779

車両が顧客2187に到着する時刻は、[12418.87473156]
車両が顧客2188に到着する時刻は、[12428.30871269]
車両が顧客2189に到着する時刻は、[12434.71183693]
車両が顧客2190に到着する時刻は、[12442.95804818]
車両が顧客2191に到着する時刻は、[12447.43018414]
車両が顧客2192に到着する時刻は、[12452.52920365]
車両が顧客2193に到着する時刻は、[12457.62822316]
車両が顧客2194に到着する時刻は、[12468.06852967]
車両が顧客2195に到着する時刻は、[12474.7767336]
車両が顧客2196に到着する時刻は、[12481.48493754]
車両が顧客2197に到着する時刻は、[12484.31336466]
車両が顧客2198に到着する時刻は、[12486.54943264]
車両が顧客2199に到着する時刻は、[12489.7117103]
車両が顧客2200に到着する時刻は、[12491.94777828]
車両が顧客2201に到着する時刻は、[12492.94777828]
車両が顧客2202に到着する時刻は、[12502.94777828]
車両が顧客2203に到着する時刻は、[12511.01003603]
車両が顧客2204に到着する時刻は、[12515.13314165]
車両が顧客2205に到着する時刻は、[12520.13314165]
車両が顧客2206に到着する時刻は、[12525.13314165]
車両が顧客2207に到着する時刻は、[12528.73869293]
車両が顧客2208に到着する時刻は、[12535.80976074]
車両が顧客2209に到着する時刻は、[12544.35376448]
車両が顧客2210に到着する時刻は、[12555.1240941]
車両が顧客2211に到着する時刻は、[12563.72641937]
車両が顧客2212に到着する時刻は、[12566.88869703]
車両が顧客2213に到着する時刻は、[12575.83296894]
車両が顧客2214に到着する時刻は、[12579.43852021]
車両が顧客2215に到着する時刻は、[1258

車両が顧客2428に到着する時刻は、[13830.47288391]
車両が顧客2429に到着する時刻は、[13835.47288391]
車両が顧客2430に到着する時刻は、[13842.54395172]
車両が顧客2431に到着する時刻は、[13845.70622939]
車両が顧客2432に到着する時刻は、[13847.70622939]
車両が顧客2433に到着する時刻は、[13849.12044295]
車両が顧客2434に到着する時刻は、[13853.12044295]
車両が顧客2435に到着する時刻は、[13857.36308363]
車両が顧客2436に到着する時刻は、[13862.36308363]
車両が顧客2437に到着する時刻は、[13864.59915161]
車両が顧客2438に到着する時刻は、[13866.83521959]
車両が顧客2439に到着する時刻は、[13872.49207384]
車両が顧客2440に到着する時刻は、[13877.59109335]
車両が顧客2441に到着する時刻は、[13882.97625816]
車両が顧客2442に到着する時刻は、[13891.52026191]
車両が顧客2443に到着する時刻は、[13897.60302444]
車両が顧客2444に到着する時刻は、[13907.80106346]
車両が顧客2445に到着する時刻は、[13913.45791771]
車両が顧客2446に到着する時刻は、[13916.62019537]
車両が顧客2447に到着する時刻は、[13924.23596848]
車両が顧客2448に到着する時刻は、[13933.45551294]
車両が顧客2449に到着する時刻は、[13935.69158091]
車両が顧客2450に到着する時刻は、[13939.29713219]
車両が顧客2451に到着する時刻は、[13940.29713219]
車両が顧客2452に到着する時刻は、[13947.50823474]
車両が顧客2453に到着する時刻は、[13948.9224483]
車両が顧客2454に到着する時刻は、[13954.7534002]
車両が顧客2455に到着する時刻は、[13961.15652443]
車両が顧客2456に到着する時刻は、[139

車両が顧客2807に到着する時刻は、[16013.97812809]
車両が顧客2808に到着する時刻は、[16015.39234166]
車両が顧客2809に到着する時刻は、[16023.20259133]
車両が顧客2810に到着する時刻は、[16024.20259133]
車両が顧客2811に到着する時刻は、[16027.03101846]
車両が顧客2812に到着する時刻は、[16031.27365914]
車両が顧客2813に到着する時刻は、[16038.88943225]
車両が顧客2814に到着する時刻は、[16043.01253788]
車両が顧客2815に到着する時刻は、[16049.72074181]
車両が顧客2816に到着する時刻は、[16057.53099148]
車両が顧客2817に到着する時刻は、[16063.61375401]
車両が顧客2818に到着する時刻は、[16066.61375401]
車両が顧客2819に到着する時刻は、[16071.99891882]
車両が顧客2820に到着する時刻は、[16078.08168135]
車両が顧客2821に到着する時刻は、[16079.49589491]
車両が顧客2822に到着する時刻は、[16087.11166802]
車両が顧客2823に到着する時刻は、[16095.65567177]
車両が顧客2824に到着する時刻は、[16102.72673958]
車両が顧客2825に到着する時刻は、[16108.55769147]
車両が顧客2826に到着する時刻は、[16110.79375945]
車両が顧客2827に到着する時刻は、[16120.01330391]
車両が顧客2828に到着する時刻は、[16122.01330391]
車両が顧客2829に到着する時刻は、[16125.61885518]
車両が顧客2830に到着する時刻は、[16128.78113284]
車両が顧客2831に到着する時刻は、[16133.88015236]
車両が顧客2832に到着する時刻は、[16137.04243002]
車両が顧客2833に到着する時刻は、[16142.87338191]
車両が顧客2834に到着する時刻は、[16148.25854672]
車両が顧客2835に到着する時刻は、[1

車両が顧客3042に到着する時刻は、[17334.72768922]
車両が顧客3043に到着する時刻は、[17335.72768922]
車両が顧客3044に到着する時刻は、[17338.72768922]
車両が顧客3045に到着する時刻は、[17342.9703299]
車両が顧客3046に到着する時刻は、[17350.25043979]
車両が顧客3047に到着する時刻は、[17355.25043979]
車両が顧客3048に到着する時刻は、[17361.95864372]
車両が顧客3049に到着する時刻は、[17363.37285729]
車両が顧客3050に到着する時刻は、[17368.37285729]
車両が顧客3051に到着する時刻は、[17370.60892526]
車両が顧客3052に到着する時刻は、[17372.84499324]
車両が顧客3053に到着する時刻は、[17380.12510313]
車両が顧客3054に到着する時刻は、[17385.12510313]
車両が顧客3055に到着する時刻は、[17393.7274284]
車両が顧客3056に到着する時刻は、[17401.97363965]
車両が顧客3057に到着する時刻は、[17404.80206677]
車両が顧客3058に到着する時刻は、[17412.08217666]
車両が顧客3059に到着する時刻は、[17413.08217666]
車両が顧客3060に到着する時刻は、[17419.4853009]
車両が顧客3061に到着する時刻は、[17426.55636871]
車両が顧客3062に到着する時刻は、[17431.94153352]
車両が顧客3063に到着する時刻は、[17435.5470848]
車両が顧客3064に到着する時刻は、[17445.5470848]
車両が顧客3065に到着する時刻は、[17456.17723061]
車両が顧客3066に到着する時刻は、[17461.56239542]
車両が顧客3067に到着する時刻は、[17466.56239542]
車両が顧客3068に到着する時刻は、[17473.63346323]
車両が顧客3069に到着する時刻は、[17480.84456578]
車両が顧客3070に到着する時刻は、[17486.

車両が顧客1003に到着する時刻は、[13252.33904357]
車両が顧客1004に到着する時刻は、[13257.43806309]
車両が顧客1005に到着する時刻は、[13261.04361436]
車両が顧客1006に到着する時刻は、[13270.9431093]
車両が顧客1007に到着する時刻は、[13280.9431093]
車両が顧客1008に到着する時刻は、[13291.14114833]
車両が顧客1009に到着する時刻は、[13293.96957545]
車両が顧客1010に到着する時刻は、[13298.09268108]
車両が顧客1011に到着する時刻は、[13307.94153888]
車両が顧客1012に到着する時刻は、[13312.0646445]
車両が顧客1013に到着する時刻は、[13316.30728519]
車両が顧客1014に到着する時刻は、[13323.378353]
車両が顧客1015に到着する時刻は、[13326.54063066]
車両が顧客1016に到着する時刻は、[13327.95484422]
車両が顧客1017に到着する時刻は、[13337.95484422]
車両が顧客1018に到着する時刻は、[13347.95484422]
車両が顧客1019に到着する時刻は、[13350.1909122]
車両が顧客1020に到着する時刻は、[13353.79646348]
車両が顧客1021に到着する時刻は、[13357.9195691]
車両が顧客1022に到着する時刻は、[13364.32269334]
車両が顧客1023に到着する時刻は、[13370.64724866]
車両が顧客1024に到着する時刻は、[13372.06146222]
車両が顧客1025に到着する時刻は、[13380.5467436]
車両が顧客1026に到着する時刻は、[13382.78281157]
車両が顧客1027に到着する時刻は、[13388.78281157]
車両が顧客1028に到着する時刻は、[13397.38513684]
車両が顧客1029に到着する時刻は、[13404.09334077]
車両が顧客1030に到着する時刻は、[13413.03761268]
車両が顧客1031に到着する時刻は、[13415.037

車両が顧客1974に到着する時刻は、[18799.27709048]
車両が顧客1975に到着する時刻は、[18808.49663494]
車両が顧客1976に到着する時刻は、[18808.49663494]
車両が顧客1977に到着する時刻は、[18817.04063868]
車両が顧客1978に到着する時刻は、[18823.12340121]
車両が顧客1979に到着する時刻は、[18829.52652545]
車両が顧客1980に到着する時刻は、[18833.99866141]
車両が顧客1981に到着する時刻は、[18839.8296133]
車両が顧客1982に到着する時刻は、[18849.72910824]
車両が顧客1983に到着する時刻は、[18853.97174893]
車両が顧客1984に到着する時刻は、[18858.44388488]
車両が顧客1985に到着する時刻は、[18861.44388488]
車両が顧客1986に到着する時刻は、[18869.98788863]
車両が顧客1987に到着する時刻は、[18878.59021389]
車両が顧客1988に到着する時刻は、[18889.0305204]
車両が顧客1989に到着する時刻は、[18897.09277815]
車両が顧客1990に到着する時刻は、[18904.70855126]
車両が顧客1991に到着する時刻は、[18913.76393639]
車両が顧客1992に到着する時刻は、[18920.83500421]
車両が顧客1993に到着する時刻は、[18923.07107218]
車両が顧客1994に到着する時刻は、[18929.15383471]
車両が顧客1995に到着する時刻は、[18937.69783846]
車両が顧客1996に到着する時刻は、[18946.30016373]
車両が顧客1997に到着する時刻は、[18955.24443564]
車両が顧客1998に到着する時刻は、[18959.24443564]
車両が顧客1999に到着する時刻は、[18964.34345515]
車両が顧客2000に到着する時刻は、[18975.16010898]
車両が顧客2001に到着する時刻は、[18986.82201277]
車両が顧客2002に到着する時刻は、[189

車両が顧客2543に到着する時刻は、[22156.85784413]
車両が顧客2544に到着する時刻は、[22160.02012179]
車両が顧客2545に到着する時刻は、[22162.84854891]
車両が顧客2546に到着する時刻は、[22165.08461689]
車両が顧客2547に到着する時刻は、[22169.20772251]
車両が顧客2548に到着する時刻は、[22172.81327379]
車両が顧客2549に到着する時刻は、[22175.81327379]
車両が顧客2550に到着する時刻は、[22182.52147772]
車両が顧客2551に到着する時刻は、[22189.22968165]
車両が顧客2552に到着する時刻は、[22195.55423698]
車両が顧客2553に到着する時刻は、[22203.61649472]
車両が顧客2554に到着する時刻は、[22213.46535253]
車両が顧客2555に到着する時刻は、[22219.78990785]
車両が顧客2556に到着する時刻は、[22221.20412141]
車両が顧客2557に到着する時刻は、[22228.81989451]
車両が顧客2558に到着する時刻は、[22236.88215226]
車両が顧客2559に到着する時刻は、[22241.35428822]
車両が顧客2560に到着する時刻は、[22249.16453789]
車両が顧客2561に到着する時刻は、[22257.22679564]
車両が顧客2562に到着する時刻は、[22261.34990127]
車両が顧客2563に到着する時刻は、[22267.00675552]
車両が顧客2564に到着する時刻は、[22269.00675552]
車両が顧客2565に到着する時刻は、[22271.00675552]
車両が顧客2566に到着する時刻は、[22282.40850977]
車両が顧客2567に到着する時刻は、[22290.65472102]
車両が顧客2568に到着する時刻は、[22297.65472102]
車両が顧客2569に到着する時刻は、[22303.73748355]
車両が顧客2570に到着する時刻は、[22309.12264836]
車両が顧客2571に到着する時刻は、[2

In [ ]:
for v in former_x.getVars():
    print('%s %g %g' % (v.varName, v.x, v.VBasis))

In [ ]:
for v in latter_x.getVars():
    print('%s %g %g' % (v.varName, v.x, v.VBasis))

In [ ]:
for constr in former_x.getConstrs()+latter_x.getConstrs():
    print(constr.Pi, constr.CBasis)

### 3. 前半後半それぞれのPrimalの最適解を、全体のDualに入れて解く

In [16]:
# 初期解の保存
basis_like = np.array([constr.Pi for constr in former_x.getConstrs()+latter_x.getConstrs()])
y3 = np.zeros((Ax.shape[0]-basis_like.shape[0],))
basis_like = np.append(basis_like, y3)

In [ ]:
print(f"Ax.T.shape={Ax.T.shape}\t\t\tAp.T.shape={Ap.T.shape}")
for Ax_i, Ap_i in zip(Ax.T, Ap.T):
    print(Ax_i, "\t", Ap_i)

In [17]:
# Gurobiによって最適解を求める
whole_y = solve_dual(Ax, Ap, b, c, instance_name+"whole_y", basis_like.shape[0], basis_like)

Gurobi Optimizer version 9.0.2 build v9.0.2rc0 (mac64)
Optimize a model with 31609 rows, 18965 columns and 56895 nonzeros
Model fingerprint: 0xd26099ab
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 2e+04]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]

Concurrent LP optimizer: dual simplex and barrier
Showing barrier log only...

Presolve removed 31602 rows and 18956 columns
Presolve time: 0.12s
Presolved: 7 rows, 9 columns, 18 nonzeros

Ordering time: 0.00s

Barrier performed 0 iterations in 0.13 seconds
Barrier solve interrupted - model solved by another algorithm


Solved with dual simplex
Solved in 2 iterations and 0.15 seconds
Optimal objective  4.388760208e+07
主問題における制約0の潜在価格は、[6317.]
主問題における制約1の潜在価格は、[6318.]
主問題における制約2の潜在価格は、[6319.]
主問題における制約3の潜在価格は、[6318.]
主問題における制約4の潜在価格は、[6317.]
主問題における制約5の潜在価格は、[6316.]
主問題における制約6の潜在価格は、[6315.]
主問題における制約7の潜在価格は、[6314.]
主問題における制約8の潜在価格は、[6313.]
主問題における制約9の潜在価格は、[6312.]
主問題における制約10の潜在価

主問題における制約624の潜在価格は、[5697.]
主問題における制約625の潜在価格は、[5696.]
主問題における制約626の潜在価格は、[5695.]
主問題における制約627の潜在価格は、[5694.]
主問題における制約628の潜在価格は、[5693.]
主問題における制約629の潜在価格は、[5692.]
主問題における制約630の潜在価格は、[5691.]
主問題における制約631の潜在価格は、[5690.]
主問題における制約632の潜在価格は、[5689.]
主問題における制約633の潜在価格は、[5688.]
主問題における制約634の潜在価格は、[5687.]
主問題における制約635の潜在価格は、[5686.]
主問題における制約636の潜在価格は、[5685.]
主問題における制約637の潜在価格は、[5684.]
主問題における制約638の潜在価格は、[5683.]
主問題における制約639の潜在価格は、[5682.]
主問題における制約640の潜在価格は、[5681.]
主問題における制約641の潜在価格は、[5680.]
主問題における制約642の潜在価格は、[5679.]
主問題における制約643の潜在価格は、[5678.]
主問題における制約644の潜在価格は、[5677.]
主問題における制約645の潜在価格は、[5676.]
主問題における制約646の潜在価格は、[5675.]
主問題における制約647の潜在価格は、[5674.]
主問題における制約648の潜在価格は、[5673.]
主問題における制約649の潜在価格は、[5672.]
主問題における制約650の潜在価格は、[5671.]
主問題における制約651の潜在価格は、[5670.]
主問題における制約652の潜在価格は、[5669.]
主問題における制約653の潜在価格は、[5668.]
主問題における制約654の潜在価格は、[5667.]
主問題における制約655の潜在価格は、[5666.]
主問題における制約656の潜在価格は、[5665.]
主問題における制約657の潜在価格は、[5664.]
主問題における制約658の潜在価格は、[5663.]
主問題における制約659の潜在価格は、[5662.]
主問題における制約660の潜在価格は、[5661.]
主

主問題における制約1266の潜在価格は、[5055.]
主問題における制約1267の潜在価格は、[5054.]
主問題における制約1268の潜在価格は、[5053.]
主問題における制約1269の潜在価格は、[5052.]
主問題における制約1270の潜在価格は、[5051.]
主問題における制約1271の潜在価格は、[5050.]
主問題における制約1272の潜在価格は、[5049.]
主問題における制約1273の潜在価格は、[5048.]
主問題における制約1274の潜在価格は、[5047.]
主問題における制約1275の潜在価格は、[5046.]
主問題における制約1276の潜在価格は、[5045.]
主問題における制約1277の潜在価格は、[5044.]
主問題における制約1278の潜在価格は、[5043.]
主問題における制約1279の潜在価格は、[5042.]
主問題における制約1280の潜在価格は、[5041.]
主問題における制約1281の潜在価格は、[5040.]
主問題における制約1282の潜在価格は、[5039.]
主問題における制約1283の潜在価格は、[5038.]
主問題における制約1284の潜在価格は、[5037.]
主問題における制約1285の潜在価格は、[5036.]
主問題における制約1286の潜在価格は、[5035.]
主問題における制約1287の潜在価格は、[5034.]
主問題における制約1288の潜在価格は、[5033.]
主問題における制約1289の潜在価格は、[5032.]
主問題における制約1290の潜在価格は、[5031.]
主問題における制約1291の潜在価格は、[5030.]
主問題における制約1292の潜在価格は、[5029.]
主問題における制約1293の潜在価格は、[5028.]
主問題における制約1294の潜在価格は、[5027.]
主問題における制約1295の潜在価格は、[5026.]
主問題における制約1296の潜在価格は、[5025.]
主問題における制約1297の潜在価格は、[5024.]
主問題における制約1298の潜在価格は、[5023.]
主問題における制約1299の潜在価格は、[5022.]
主問題における制約1300の潜在価格は、[5021.]
主問題における制約1301の潜在価格は、

主問題における制約1575の潜在価格は、[4746.]
主問題における制約1576の潜在価格は、[4745.]
主問題における制約1577の潜在価格は、[4744.]
主問題における制約1578の潜在価格は、[4743.]
主問題における制約1579の潜在価格は、[4742.]
主問題における制約1580の潜在価格は、[4741.]
主問題における制約1581の潜在価格は、[4740.]
主問題における制約1582の潜在価格は、[4739.]
主問題における制約1583の潜在価格は、[4738.]
主問題における制約1584の潜在価格は、[4737.]
主問題における制約1585の潜在価格は、[4736.]
主問題における制約1586の潜在価格は、[4735.]
主問題における制約1587の潜在価格は、[4734.]
主問題における制約1588の潜在価格は、[4733.]
主問題における制約1589の潜在価格は、[4732.]
主問題における制約1590の潜在価格は、[4731.]
主問題における制約1591の潜在価格は、[4730.]
主問題における制約1592の潜在価格は、[4729.]
主問題における制約1593の潜在価格は、[4728.]
主問題における制約1594の潜在価格は、[4727.]
主問題における制約1595の潜在価格は、[4726.]
主問題における制約1596の潜在価格は、[4725.]
主問題における制約1597の潜在価格は、[4724.]
主問題における制約1598の潜在価格は、[4723.]
主問題における制約1599の潜在価格は、[4722.]
主問題における制約1600の潜在価格は、[4721.]
主問題における制約1601の潜在価格は、[4720.]
主問題における制約1602の潜在価格は、[4719.]
主問題における制約1603の潜在価格は、[4718.]
主問題における制約1604の潜在価格は、[4717.]
主問題における制約1605の潜在価格は、[4716.]
主問題における制約1606の潜在価格は、[4715.]
主問題における制約1607の潜在価格は、[4714.]
主問題における制約1608の潜在価格は、[4713.]
主問題における制約1609の潜在価格は、[4712.]
主問題における制約1610の潜在価格は、

主問題における制約1906の潜在価格は、[4415.]
主問題における制約1907の潜在価格は、[4414.]
主問題における制約1908の潜在価格は、[4413.]
主問題における制約1909の潜在価格は、[4412.]
主問題における制約1910の潜在価格は、[4411.]
主問題における制約1911の潜在価格は、[4410.]
主問題における制約1912の潜在価格は、[4409.]
主問題における制約1913の潜在価格は、[4408.]
主問題における制約1914の潜在価格は、[4407.]
主問題における制約1915の潜在価格は、[4406.]
主問題における制約1916の潜在価格は、[4405.]
主問題における制約1917の潜在価格は、[4404.]
主問題における制約1918の潜在価格は、[4403.]
主問題における制約1919の潜在価格は、[4402.]
主問題における制約1920の潜在価格は、[4401.]
主問題における制約1921の潜在価格は、[4400.]
主問題における制約1922の潜在価格は、[4399.]
主問題における制約1923の潜在価格は、[4398.]
主問題における制約1924の潜在価格は、[4397.]
主問題における制約1925の潜在価格は、[4396.]
主問題における制約1926の潜在価格は、[4395.]
主問題における制約1927の潜在価格は、[4394.]
主問題における制約1928の潜在価格は、[4393.]
主問題における制約1929の潜在価格は、[4392.]
主問題における制約1930の潜在価格は、[4391.]
主問題における制約1931の潜在価格は、[4390.]
主問題における制約1932の潜在価格は、[4389.]
主問題における制約1933の潜在価格は、[4388.]
主問題における制約1934の潜在価格は、[4387.]
主問題における制約1935の潜在価格は、[4386.]
主問題における制約1936の潜在価格は、[4385.]
主問題における制約1937の潜在価格は、[4384.]
主問題における制約1938の潜在価格は、[4383.]
主問題における制約1939の潜在価格は、[4382.]
主問題における制約1940の潜在価格は、[4381.]
主問題における制約1941の潜在価格は、

主問題における制約2215の潜在価格は、[4106.]
主問題における制約2216の潜在価格は、[4105.]
主問題における制約2217の潜在価格は、[4104.]
主問題における制約2218の潜在価格は、[4103.]
主問題における制約2219の潜在価格は、[4102.]
主問題における制約2220の潜在価格は、[4101.]
主問題における制約2221の潜在価格は、[4100.]
主問題における制約2222の潜在価格は、[4099.]
主問題における制約2223の潜在価格は、[4098.]
主問題における制約2224の潜在価格は、[4097.]
主問題における制約2225の潜在価格は、[4096.]
主問題における制約2226の潜在価格は、[4095.]
主問題における制約2227の潜在価格は、[4094.]
主問題における制約2228の潜在価格は、[4093.]
主問題における制約2229の潜在価格は、[4092.]
主問題における制約2230の潜在価格は、[4091.]
主問題における制約2231の潜在価格は、[4090.]
主問題における制約2232の潜在価格は、[4089.]
主問題における制約2233の潜在価格は、[4088.]
主問題における制約2234の潜在価格は、[4087.]
主問題における制約2235の潜在価格は、[4086.]
主問題における制約2236の潜在価格は、[4085.]
主問題における制約2237の潜在価格は、[4084.]
主問題における制約2238の潜在価格は、[4083.]
主問題における制約2239の潜在価格は、[4082.]
主問題における制約2240の潜在価格は、[4081.]
主問題における制約2241の潜在価格は、[4080.]
主問題における制約2242の潜在価格は、[4079.]
主問題における制約2243の潜在価格は、[4078.]
主問題における制約2244の潜在価格は、[4077.]
主問題における制約2245の潜在価格は、[4076.]
主問題における制約2246の潜在価格は、[4075.]
主問題における制約2247の潜在価格は、[4074.]
主問題における制約2248の潜在価格は、[4073.]
主問題における制約2249の潜在価格は、[4072.]
主問題における制約2250の潜在価格は、

主問題における制約2527の潜在価格は、[3794.]
主問題における制約2528の潜在価格は、[3793.]
主問題における制約2529の潜在価格は、[3792.]
主問題における制約2530の潜在価格は、[3791.]
主問題における制約2531の潜在価格は、[3790.]
主問題における制約2532の潜在価格は、[3789.]
主問題における制約2533の潜在価格は、[3788.]
主問題における制約2534の潜在価格は、[3787.]
主問題における制約2535の潜在価格は、[3786.]
主問題における制約2536の潜在価格は、[3785.]
主問題における制約2537の潜在価格は、[3784.]
主問題における制約2538の潜在価格は、[3783.]
主問題における制約2539の潜在価格は、[3782.]
主問題における制約2540の潜在価格は、[3781.]
主問題における制約2541の潜在価格は、[3780.]
主問題における制約2542の潜在価格は、[3779.]
主問題における制約2543の潜在価格は、[3778.]
主問題における制約2544の潜在価格は、[3777.]
主問題における制約2545の潜在価格は、[3776.]
主問題における制約2546の潜在価格は、[3775.]
主問題における制約2547の潜在価格は、[3774.]
主問題における制約2548の潜在価格は、[3773.]
主問題における制約2549の潜在価格は、[3772.]
主問題における制約2550の潜在価格は、[3771.]
主問題における制約2551の潜在価格は、[3770.]
主問題における制約2552の潜在価格は、[3769.]
主問題における制約2553の潜在価格は、[3768.]
主問題における制約2554の潜在価格は、[3767.]
主問題における制約2555の潜在価格は、[3766.]
主問題における制約2556の潜在価格は、[3765.]
主問題における制約2557の潜在価格は、[3764.]
主問題における制約2558の潜在価格は、[3763.]
主問題における制約2559の潜在価格は、[3762.]
主問題における制約2560の潜在価格は、[3761.]
主問題における制約2561の潜在価格は、[3760.]
主問題における制約2562の潜在価格は、

主問題における制約2853の潜在価格は、[3468.]
主問題における制約2854の潜在価格は、[3467.]
主問題における制約2855の潜在価格は、[3466.]
主問題における制約2856の潜在価格は、[3465.]
主問題における制約2857の潜在価格は、[3464.]
主問題における制約2858の潜在価格は、[3463.]
主問題における制約2859の潜在価格は、[3462.]
主問題における制約2860の潜在価格は、[3461.]
主問題における制約2861の潜在価格は、[3460.]
主問題における制約2862の潜在価格は、[3459.]
主問題における制約2863の潜在価格は、[3458.]
主問題における制約2864の潜在価格は、[3457.]
主問題における制約2865の潜在価格は、[3456.]
主問題における制約2866の潜在価格は、[3455.]
主問題における制約2867の潜在価格は、[3454.]
主問題における制約2868の潜在価格は、[3453.]
主問題における制約2869の潜在価格は、[3452.]
主問題における制約2870の潜在価格は、[3451.]
主問題における制約2871の潜在価格は、[3450.]
主問題における制約2872の潜在価格は、[3449.]
主問題における制約2873の潜在価格は、[3448.]
主問題における制約2874の潜在価格は、[3447.]
主問題における制約2875の潜在価格は、[3446.]
主問題における制約2876の潜在価格は、[3445.]
主問題における制約2877の潜在価格は、[3444.]
主問題における制約2878の潜在価格は、[3443.]
主問題における制約2879の潜在価格は、[3442.]
主問題における制約2880の潜在価格は、[3441.]
主問題における制約2881の潜在価格は、[3440.]
主問題における制約2882の潜在価格は、[3439.]
主問題における制約2883の潜在価格は、[3438.]
主問題における制約2884の潜在価格は、[3437.]
主問題における制約2885の潜在価格は、[3436.]
主問題における制約2886の潜在価格は、[3435.]
主問題における制約2887の潜在価格は、[3434.]
主問題における制約2888の潜在価格は、

主問題における制約3189の潜在価格は、[3132.]
主問題における制約3190の潜在価格は、[3131.]
主問題における制約3191の潜在価格は、[3130.]
主問題における制約3192の潜在価格は、[3129.]
主問題における制約3193の潜在価格は、[3128.]
主問題における制約3194の潜在価格は、[3127.]
主問題における制約3195の潜在価格は、[3126.]
主問題における制約3196の潜在価格は、[3125.]
主問題における制約3197の潜在価格は、[3124.]
主問題における制約3198の潜在価格は、[3123.]
主問題における制約3199の潜在価格は、[3122.]
主問題における制約3200の潜在価格は、[3121.]
主問題における制約3201の潜在価格は、[3120.]
主問題における制約3202の潜在価格は、[3119.]
主問題における制約3203の潜在価格は、[3118.]
主問題における制約3204の潜在価格は、[3117.]
主問題における制約3205の潜在価格は、[3116.]
主問題における制約3206の潜在価格は、[3115.]
主問題における制約3207の潜在価格は、[3114.]
主問題における制約3208の潜在価格は、[3113.]
主問題における制約3209の潜在価格は、[3112.]
主問題における制約3210の潜在価格は、[3111.]
主問題における制約3211の潜在価格は、[3110.]
主問題における制約3212の潜在価格は、[3109.]
主問題における制約3213の潜在価格は、[3108.]
主問題における制約3214の潜在価格は、[3107.]
主問題における制約3215の潜在価格は、[3106.]
主問題における制約3216の潜在価格は、[3105.]
主問題における制約3217の潜在価格は、[3104.]
主問題における制約3218の潜在価格は、[3103.]
主問題における制約3219の潜在価格は、[3102.]
主問題における制約3220の潜在価格は、[3101.]
主問題における制約3221の潜在価格は、[3100.]
主問題における制約3222の潜在価格は、[3099.]
主問題における制約3223の潜在価格は、[3098.]
主問題における制約3224の潜在価格は、

主問題における制約3483の潜在価格は、[2838.]
主問題における制約3484の潜在価格は、[2837.]
主問題における制約3485の潜在価格は、[2836.]
主問題における制約3486の潜在価格は、[2835.]
主問題における制約3487の潜在価格は、[2834.]
主問題における制約3488の潜在価格は、[2833.]
主問題における制約3489の潜在価格は、[2832.]
主問題における制約3490の潜在価格は、[2831.]
主問題における制約3491の潜在価格は、[2830.]
主問題における制約3492の潜在価格は、[2829.]
主問題における制約3493の潜在価格は、[2828.]
主問題における制約3494の潜在価格は、[2827.]
主問題における制約3495の潜在価格は、[2826.]
主問題における制約3496の潜在価格は、[2825.]
主問題における制約3497の潜在価格は、[2824.]
主問題における制約3498の潜在価格は、[2823.]
主問題における制約3499の潜在価格は、[2822.]
主問題における制約3500の潜在価格は、[2821.]
主問題における制約3501の潜在価格は、[2820.]
主問題における制約3502の潜在価格は、[2819.]
主問題における制約3503の潜在価格は、[2818.]
主問題における制約3504の潜在価格は、[2817.]
主問題における制約3505の潜在価格は、[2816.]
主問題における制約3506の潜在価格は、[2815.]
主問題における制約3507の潜在価格は、[2814.]
主問題における制約3508の潜在価格は、[2813.]
主問題における制約3509の潜在価格は、[2812.]
主問題における制約3510の潜在価格は、[2811.]
主問題における制約3511の潜在価格は、[2810.]
主問題における制約3512の潜在価格は、[2809.]
主問題における制約3513の潜在価格は、[2808.]
主問題における制約3514の潜在価格は、[2807.]
主問題における制約3515の潜在価格は、[2806.]
主問題における制約3516の潜在価格は、[2805.]
主問題における制約3517の潜在価格は、[2804.]
主問題における制約3518の潜在価格は、

主問題における制約3864の潜在価格は、[2457.]
主問題における制約3865の潜在価格は、[2456.]
主問題における制約3866の潜在価格は、[2455.]
主問題における制約3867の潜在価格は、[2454.]
主問題における制約3868の潜在価格は、[2453.]
主問題における制約3869の潜在価格は、[2452.]
主問題における制約3870の潜在価格は、[2451.]
主問題における制約3871の潜在価格は、[2450.]
主問題における制約3872の潜在価格は、[2449.]
主問題における制約3873の潜在価格は、[2448.]
主問題における制約3874の潜在価格は、[2447.]
主問題における制約3875の潜在価格は、[2446.]
主問題における制約3876の潜在価格は、[2445.]
主問題における制約3877の潜在価格は、[2444.]
主問題における制約3878の潜在価格は、[2443.]
主問題における制約3879の潜在価格は、[2442.]
主問題における制約3880の潜在価格は、[2441.]
主問題における制約3881の潜在価格は、[2440.]
主問題における制約3882の潜在価格は、[2439.]
主問題における制約3883の潜在価格は、[2438.]
主問題における制約3884の潜在価格は、[2437.]
主問題における制約3885の潜在価格は、[2436.]
主問題における制約3886の潜在価格は、[2435.]
主問題における制約3887の潜在価格は、[2434.]
主問題における制約3888の潜在価格は、[2433.]
主問題における制約3889の潜在価格は、[2432.]
主問題における制約3890の潜在価格は、[2431.]
主問題における制約3891の潜在価格は、[2430.]
主問題における制約3892の潜在価格は、[2429.]
主問題における制約3893の潜在価格は、[2428.]
主問題における制約3894の潜在価格は、[2427.]
主問題における制約3895の潜在価格は、[2426.]
主問題における制約3896の潜在価格は、[2425.]
主問題における制約3897の潜在価格は、[2424.]
主問題における制約3898の潜在価格は、[2423.]
主問題における制約3899の潜在価格は、

主問題における制約4184の潜在価格は、[2137.]
主問題における制約4185の潜在価格は、[2136.]
主問題における制約4186の潜在価格は、[2135.]
主問題における制約4187の潜在価格は、[2134.]
主問題における制約4188の潜在価格は、[2133.]
主問題における制約4189の潜在価格は、[2132.]
主問題における制約4190の潜在価格は、[2131.]
主問題における制約4191の潜在価格は、[2130.]
主問題における制約4192の潜在価格は、[2129.]
主問題における制約4193の潜在価格は、[2128.]
主問題における制約4194の潜在価格は、[2127.]
主問題における制約4195の潜在価格は、[2126.]
主問題における制約4196の潜在価格は、[2125.]
主問題における制約4197の潜在価格は、[2124.]
主問題における制約4198の潜在価格は、[2123.]
主問題における制約4199の潜在価格は、[2122.]
主問題における制約4200の潜在価格は、[2121.]
主問題における制約4201の潜在価格は、[2120.]
主問題における制約4202の潜在価格は、[2119.]
主問題における制約4203の潜在価格は、[2118.]
主問題における制約4204の潜在価格は、[2117.]
主問題における制約4205の潜在価格は、[2116.]
主問題における制約4206の潜在価格は、[2115.]
主問題における制約4207の潜在価格は、[2114.]
主問題における制約4208の潜在価格は、[2113.]
主問題における制約4209の潜在価格は、[2112.]
主問題における制約4210の潜在価格は、[2111.]
主問題における制約4211の潜在価格は、[2110.]
主問題における制約4212の潜在価格は、[2109.]
主問題における制約4213の潜在価格は、[2108.]
主問題における制約4214の潜在価格は、[2107.]
主問題における制約4215の潜在価格は、[2106.]
主問題における制約4216の潜在価格は、[2105.]
主問題における制約4217の潜在価格は、[2104.]
主問題における制約4218の潜在価格は、[2103.]
主問題における制約4219の潜在価格は、

主問題における制約4486の潜在価格は、[1835.]
主問題における制約4487の潜在価格は、[1834.]
主問題における制約4488の潜在価格は、[1833.]
主問題における制約4489の潜在価格は、[1832.]
主問題における制約4490の潜在価格は、[1831.]
主問題における制約4491の潜在価格は、[1830.]
主問題における制約4492の潜在価格は、[1829.]
主問題における制約4493の潜在価格は、[1828.]
主問題における制約4494の潜在価格は、[1827.]
主問題における制約4495の潜在価格は、[1826.]
主問題における制約4496の潜在価格は、[1825.]
主問題における制約4497の潜在価格は、[1824.]
主問題における制約4498の潜在価格は、[1823.]
主問題における制約4499の潜在価格は、[1822.]
主問題における制約4500の潜在価格は、[1821.]
主問題における制約4501の潜在価格は、[1820.]
主問題における制約4502の潜在価格は、[1819.]
主問題における制約4503の潜在価格は、[1818.]
主問題における制約4504の潜在価格は、[1817.]
主問題における制約4505の潜在価格は、[1816.]
主問題における制約4506の潜在価格は、[1815.]
主問題における制約4507の潜在価格は、[1814.]
主問題における制約4508の潜在価格は、[1813.]
主問題における制約4509の潜在価格は、[1812.]
主問題における制約4510の潜在価格は、[1811.]
主問題における制約4511の潜在価格は、[1810.]
主問題における制約4512の潜在価格は、[1809.]
主問題における制約4513の潜在価格は、[1808.]
主問題における制約4514の潜在価格は、[1807.]
主問題における制約4515の潜在価格は、[1806.]
主問題における制約4516の潜在価格は、[1805.]
主問題における制約4517の潜在価格は、[1804.]
主問題における制約4518の潜在価格は、[1803.]
主問題における制約4519の潜在価格は、[1802.]
主問題における制約4520の潜在価格は、[1801.]
主問題における制約4521の潜在価格は、

主問題における制約4834の潜在価格は、[1487.]
主問題における制約4835の潜在価格は、[1486.]
主問題における制約4836の潜在価格は、[1485.]
主問題における制約4837の潜在価格は、[1484.]
主問題における制約4838の潜在価格は、[1483.]
主問題における制約4839の潜在価格は、[1482.]
主問題における制約4840の潜在価格は、[1481.]
主問題における制約4841の潜在価格は、[1480.]
主問題における制約4842の潜在価格は、[1479.]
主問題における制約4843の潜在価格は、[1478.]
主問題における制約4844の潜在価格は、[1477.]
主問題における制約4845の潜在価格は、[1476.]
主問題における制約4846の潜在価格は、[1475.]
主問題における制約4847の潜在価格は、[1474.]
主問題における制約4848の潜在価格は、[1473.]
主問題における制約4849の潜在価格は、[1472.]
主問題における制約4850の潜在価格は、[1471.]
主問題における制約4851の潜在価格は、[1470.]
主問題における制約4852の潜在価格は、[1469.]
主問題における制約4853の潜在価格は、[1468.]
主問題における制約4854の潜在価格は、[1467.]
主問題における制約4855の潜在価格は、[1466.]
主問題における制約4856の潜在価格は、[1465.]
主問題における制約4857の潜在価格は、[1464.]
主問題における制約4858の潜在価格は、[1463.]
主問題における制約4859の潜在価格は、[1462.]
主問題における制約4860の潜在価格は、[1461.]
主問題における制約4861の潜在価格は、[1460.]
主問題における制約4862の潜在価格は、[1459.]
主問題における制約4863の潜在価格は、[1458.]
主問題における制約4864の潜在価格は、[1457.]
主問題における制約4865の潜在価格は、[1456.]
主問題における制約4866の潜在価格は、[1455.]
主問題における制約4867の潜在価格は、[1454.]
主問題における制約4868の潜在価格は、[1453.]
主問題における制約4869の潜在価格は、

主問題における制約5159の潜在価格は、[1162.]
主問題における制約5160の潜在価格は、[1161.]
主問題における制約5161の潜在価格は、[1160.]
主問題における制約5162の潜在価格は、[1159.]
主問題における制約5163の潜在価格は、[1158.]
主問題における制約5164の潜在価格は、[1157.]
主問題における制約5165の潜在価格は、[1156.]
主問題における制約5166の潜在価格は、[1155.]
主問題における制約5167の潜在価格は、[1154.]
主問題における制約5168の潜在価格は、[1153.]
主問題における制約5169の潜在価格は、[1152.]
主問題における制約5170の潜在価格は、[1151.]
主問題における制約5171の潜在価格は、[1150.]
主問題における制約5172の潜在価格は、[1149.]
主問題における制約5173の潜在価格は、[1148.]
主問題における制約5174の潜在価格は、[1147.]
主問題における制約5175の潜在価格は、[1146.]
主問題における制約5176の潜在価格は、[1145.]
主問題における制約5177の潜在価格は、[1144.]
主問題における制約5178の潜在価格は、[1143.]
主問題における制約5179の潜在価格は、[1142.]
主問題における制約5180の潜在価格は、[1141.]
主問題における制約5181の潜在価格は、[1140.]
主問題における制約5182の潜在価格は、[1139.]
主問題における制約5183の潜在価格は、[1138.]
主問題における制約5184の潜在価格は、[1137.]
主問題における制約5185の潜在価格は、[1136.]
主問題における制約5186の潜在価格は、[1135.]
主問題における制約5187の潜在価格は、[1134.]
主問題における制約5188の潜在価格は、[1133.]
主問題における制約5189の潜在価格は、[1132.]
主問題における制約5190の潜在価格は、[1131.]
主問題における制約5191の潜在価格は、[1130.]
主問題における制約5192の潜在価格は、[1129.]
主問題における制約5193の潜在価格は、[1128.]
主問題における制約5194の潜在価格は、

主問題における制約5456の潜在価格は、[865.]
主問題における制約5457の潜在価格は、[864.]
主問題における制約5458の潜在価格は、[863.]
主問題における制約5459の潜在価格は、[862.]
主問題における制約5460の潜在価格は、[861.]
主問題における制約5461の潜在価格は、[860.]
主問題における制約5462の潜在価格は、[859.]
主問題における制約5463の潜在価格は、[858.]
主問題における制約5464の潜在価格は、[857.]
主問題における制約5465の潜在価格は、[856.]
主問題における制約5466の潜在価格は、[855.]
主問題における制約5467の潜在価格は、[854.]
主問題における制約5468の潜在価格は、[853.]
主問題における制約5469の潜在価格は、[852.]
主問題における制約5470の潜在価格は、[851.]
主問題における制約5471の潜在価格は、[850.]
主問題における制約5472の潜在価格は、[849.]
主問題における制約5473の潜在価格は、[848.]
主問題における制約5474の潜在価格は、[847.]
主問題における制約5475の潜在価格は、[846.]
主問題における制約5476の潜在価格は、[845.]
主問題における制約5477の潜在価格は、[844.]
主問題における制約5478の潜在価格は、[843.]
主問題における制約5479の潜在価格は、[842.]
主問題における制約5480の潜在価格は、[841.]
主問題における制約5481の潜在価格は、[840.]
主問題における制約5482の潜在価格は、[839.]
主問題における制約5483の潜在価格は、[838.]
主問題における制約5484の潜在価格は、[837.]
主問題における制約5485の潜在価格は、[836.]
主問題における制約5486の潜在価格は、[835.]
主問題における制約5487の潜在価格は、[834.]
主問題における制約5488の潜在価格は、[833.]
主問題における制約5489の潜在価格は、[832.]
主問題における制約5490の潜在価格は、[831.]
主問題における制約5491の潜在価格は、[830.]
主問題における制約5492の潜在価格は、[829.]
主

主問題における制約5817の潜在価格は、[504.]
主問題における制約5818の潜在価格は、[503.]
主問題における制約5819の潜在価格は、[502.]
主問題における制約5820の潜在価格は、[501.]
主問題における制約5821の潜在価格は、[500.]
主問題における制約5822の潜在価格は、[499.]
主問題における制約5823の潜在価格は、[498.]
主問題における制約5824の潜在価格は、[497.]
主問題における制約5825の潜在価格は、[496.]
主問題における制約5826の潜在価格は、[495.]
主問題における制約5827の潜在価格は、[494.]
主問題における制約5828の潜在価格は、[493.]
主問題における制約5829の潜在価格は、[492.]
主問題における制約5830の潜在価格は、[491.]
主問題における制約5831の潜在価格は、[490.]
主問題における制約5832の潜在価格は、[489.]
主問題における制約5833の潜在価格は、[488.]
主問題における制約5834の潜在価格は、[487.]
主問題における制約5835の潜在価格は、[486.]
主問題における制約5836の潜在価格は、[485.]
主問題における制約5837の潜在価格は、[484.]
主問題における制約5838の潜在価格は、[483.]
主問題における制約5839の潜在価格は、[482.]
主問題における制約5840の潜在価格は、[481.]
主問題における制約5841の潜在価格は、[480.]
主問題における制約5842の潜在価格は、[479.]
主問題における制約5843の潜在価格は、[478.]
主問題における制約5844の潜在価格は、[477.]
主問題における制約5845の潜在価格は、[476.]
主問題における制約5846の潜在価格は、[475.]
主問題における制約5847の潜在価格は、[474.]
主問題における制約5848の潜在価格は、[473.]
主問題における制約5849の潜在価格は、[472.]
主問題における制約5850の潜在価格は、[471.]
主問題における制約5851の潜在価格は、[470.]
主問題における制約5852の潜在価格は、[469.]
主問題における制約5853の潜在価格は、[468.]
主

主問題における制約6134の潜在価格は、[187.]
主問題における制約6135の潜在価格は、[186.]
主問題における制約6136の潜在価格は、[185.]
主問題における制約6137の潜在価格は、[184.]
主問題における制約6138の潜在価格は、[183.]
主問題における制約6139の潜在価格は、[182.]
主問題における制約6140の潜在価格は、[181.]
主問題における制約6141の潜在価格は、[180.]
主問題における制約6142の潜在価格は、[179.]
主問題における制約6143の潜在価格は、[178.]
主問題における制約6144の潜在価格は、[177.]
主問題における制約6145の潜在価格は、[176.]
主問題における制約6146の潜在価格は、[175.]
主問題における制約6147の潜在価格は、[174.]
主問題における制約6148の潜在価格は、[173.]
主問題における制約6149の潜在価格は、[172.]
主問題における制約6150の潜在価格は、[171.]
主問題における制約6151の潜在価格は、[170.]
主問題における制約6152の潜在価格は、[169.]
主問題における制約6153の潜在価格は、[168.]
主問題における制約6154の潜在価格は、[167.]
主問題における制約6155の潜在価格は、[166.]
主問題における制約6156の潜在価格は、[165.]
主問題における制約6157の潜在価格は、[164.]
主問題における制約6158の潜在価格は、[163.]
主問題における制約6159の潜在価格は、[162.]
主問題における制約6160の潜在価格は、[161.]
主問題における制約6161の潜在価格は、[160.]
主問題における制約6162の潜在価格は、[159.]
主問題における制約6163の潜在価格は、[158.]
主問題における制約6164の潜在価格は、[157.]
主問題における制約6165の潜在価格は、[156.]
主問題における制約6166の潜在価格は、[155.]
主問題における制約6167の潜在価格は、[154.]
主問題における制約6168の潜在価格は、[153.]
主問題における制約6169の潜在価格は、[152.]
主問題における制約6170の潜在価格は、[151.]
主

主問題における制約6452の潜在価格は、[1.]
主問題における制約6453の潜在価格は、[0.]
主問題における制約6454の潜在価格は、[1.]
主問題における制約6455の潜在価格は、[0.]
主問題における制約6456の潜在価格は、[1.]
主問題における制約6457の潜在価格は、[0.]
主問題における制約6458の潜在価格は、[1.]
主問題における制約6459の潜在価格は、[0.]
主問題における制約6460の潜在価格は、[1.]
主問題における制約6461の潜在価格は、[0.]
主問題における制約6462の潜在価格は、[1.]
主問題における制約6463の潜在価格は、[0.]
主問題における制約6464の潜在価格は、[1.]
主問題における制約6465の潜在価格は、[0.]
主問題における制約6466の潜在価格は、[1.]
主問題における制約6467の潜在価格は、[0.]
主問題における制約6468の潜在価格は、[1.]
主問題における制約6469の潜在価格は、[0.]
主問題における制約6470の潜在価格は、[1.]
主問題における制約6471の潜在価格は、[0.]
主問題における制約6472の潜在価格は、[1.]
主問題における制約6473の潜在価格は、[0.]
主問題における制約6474の潜在価格は、[1.]
主問題における制約6475の潜在価格は、[0.]
主問題における制約6476の潜在価格は、[1.]
主問題における制約6477の潜在価格は、[0.]
主問題における制約6478の潜在価格は、[1.]
主問題における制約6479の潜在価格は、[0.]
主問題における制約6480の潜在価格は、[1.]
主問題における制約6481の潜在価格は、[0.]
主問題における制約6482の潜在価格は、[1.]
主問題における制約6483の潜在価格は、[0.]
主問題における制約6484の潜在価格は、[1.]
主問題における制約6485の潜在価格は、[0.]
主問題における制約6486の潜在価格は、[1.]
主問題における制約6487の潜在価格は、[0.]
主問題における制約6488の潜在価格は、[1.]
主問題における制約6489の潜在価格は、[0.]
主問題における制約6490の潜在価格は、[1.]
主問題における制約6491の潜在価格は、[0.]


主問題における制約6817の潜在価格は、[0.]
主問題における制約6818の潜在価格は、[1.]
主問題における制約6819の潜在価格は、[0.]
主問題における制約6820の潜在価格は、[1.]
主問題における制約6821の潜在価格は、[0.]
主問題における制約6822の潜在価格は、[1.]
主問題における制約6823の潜在価格は、[0.]
主問題における制約6824の潜在価格は、[1.]
主問題における制約6825の潜在価格は、[0.]
主問題における制約6826の潜在価格は、[1.]
主問題における制約6827の潜在価格は、[0.]
主問題における制約6828の潜在価格は、[1.]
主問題における制約6829の潜在価格は、[0.]
主問題における制約6830の潜在価格は、[1.]
主問題における制約6831の潜在価格は、[0.]
主問題における制約6832の潜在価格は、[1.]
主問題における制約6833の潜在価格は、[0.]
主問題における制約6834の潜在価格は、[1.]
主問題における制約6835の潜在価格は、[0.]
主問題における制約6836の潜在価格は、[1.]
主問題における制約6837の潜在価格は、[0.]
主問題における制約6838の潜在価格は、[1.]
主問題における制約6839の潜在価格は、[0.]
主問題における制約6840の潜在価格は、[1.]
主問題における制約6841の潜在価格は、[0.]
主問題における制約6842の潜在価格は、[1.]
主問題における制約6843の潜在価格は、[0.]
主問題における制約6844の潜在価格は、[1.]
主問題における制約6845の潜在価格は、[0.]
主問題における制約6846の潜在価格は、[1.]
主問題における制約6847の潜在価格は、[0.]
主問題における制約6848の潜在価格は、[1.]
主問題における制約6849の潜在価格は、[0.]
主問題における制約6850の潜在価格は、[1.]
主問題における制約6851の潜在価格は、[0.]
主問題における制約6852の潜在価格は、[1.]
主問題における制約6853の潜在価格は、[0.]
主問題における制約6854の潜在価格は、[1.]
主問題における制約6855の潜在価格は、[0.]
主問題における制約6856の潜在価格は、[1.]


主問題における制約7164の潜在価格は、[1.]
主問題における制約7165の潜在価格は、[0.]
主問題における制約7166の潜在価格は、[1.]
主問題における制約7167の潜在価格は、[0.]
主問題における制約7168の潜在価格は、[1.]
主問題における制約7169の潜在価格は、[0.]
主問題における制約7170の潜在価格は、[1.]
主問題における制約7171の潜在価格は、[0.]
主問題における制約7172の潜在価格は、[1.]
主問題における制約7173の潜在価格は、[0.]
主問題における制約7174の潜在価格は、[1.]
主問題における制約7175の潜在価格は、[0.]
主問題における制約7176の潜在価格は、[1.]
主問題における制約7177の潜在価格は、[0.]
主問題における制約7178の潜在価格は、[1.]
主問題における制約7179の潜在価格は、[0.]
主問題における制約7180の潜在価格は、[1.]
主問題における制約7181の潜在価格は、[0.]
主問題における制約7182の潜在価格は、[1.]
主問題における制約7183の潜在価格は、[0.]
主問題における制約7184の潜在価格は、[1.]
主問題における制約7185の潜在価格は、[0.]
主問題における制約7186の潜在価格は、[1.]
主問題における制約7187の潜在価格は、[0.]
主問題における制約7188の潜在価格は、[1.]
主問題における制約7189の潜在価格は、[0.]
主問題における制約7190の潜在価格は、[1.]
主問題における制約7191の潜在価格は、[0.]
主問題における制約7192の潜在価格は、[1.]
主問題における制約7193の潜在価格は、[0.]
主問題における制約7194の潜在価格は、[1.]
主問題における制約7195の潜在価格は、[0.]
主問題における制約7196の潜在価格は、[1.]
主問題における制約7197の潜在価格は、[0.]
主問題における制約7198の潜在価格は、[1.]
主問題における制約7199の潜在価格は、[0.]
主問題における制約7200の潜在価格は、[1.]
主問題における制約7201の潜在価格は、[0.]
主問題における制約7202の潜在価格は、[1.]
主問題における制約7203の潜在価格は、[0.]


主問題における制約7528の潜在価格は、[1.]
主問題における制約7529の潜在価格は、[0.]
主問題における制約7530の潜在価格は、[1.]
主問題における制約7531の潜在価格は、[0.]
主問題における制約7532の潜在価格は、[1.]
主問題における制約7533の潜在価格は、[0.]
主問題における制約7534の潜在価格は、[1.]
主問題における制約7535の潜在価格は、[0.]
主問題における制約7536の潜在価格は、[1.]
主問題における制約7537の潜在価格は、[0.]
主問題における制約7538の潜在価格は、[1.]
主問題における制約7539の潜在価格は、[0.]
主問題における制約7540の潜在価格は、[1.]
主問題における制約7541の潜在価格は、[0.]
主問題における制約7542の潜在価格は、[1.]
主問題における制約7543の潜在価格は、[0.]
主問題における制約7544の潜在価格は、[1.]
主問題における制約7545の潜在価格は、[0.]
主問題における制約7546の潜在価格は、[1.]
主問題における制約7547の潜在価格は、[0.]
主問題における制約7548の潜在価格は、[1.]
主問題における制約7549の潜在価格は、[0.]
主問題における制約7550の潜在価格は、[1.]
主問題における制約7551の潜在価格は、[0.]
主問題における制約7552の潜在価格は、[1.]
主問題における制約7553の潜在価格は、[0.]
主問題における制約7554の潜在価格は、[1.]
主問題における制約7555の潜在価格は、[0.]
主問題における制約7556の潜在価格は、[1.]
主問題における制約7557の潜在価格は、[0.]
主問題における制約7558の潜在価格は、[1.]
主問題における制約7559の潜在価格は、[0.]
主問題における制約7560の潜在価格は、[1.]
主問題における制約7561の潜在価格は、[0.]
主問題における制約7562の潜在価格は、[1.]
主問題における制約7563の潜在価格は、[0.]
主問題における制約7564の潜在価格は、[1.]
主問題における制約7565の潜在価格は、[0.]
主問題における制約7566の潜在価格は、[1.]
主問題における制約7567の潜在価格は、[0.]


主問題における制約7992の潜在価格は、[1.]
主問題における制約7993の潜在価格は、[0.]
主問題における制約7994の潜在価格は、[1.]
主問題における制約7995の潜在価格は、[0.]
主問題における制約7996の潜在価格は、[1.]
主問題における制約7997の潜在価格は、[0.]
主問題における制約7998の潜在価格は、[1.]
主問題における制約7999の潜在価格は、[0.]
主問題における制約8000の潜在価格は、[1.]
主問題における制約8001の潜在価格は、[0.]
主問題における制約8002の潜在価格は、[1.]
主問題における制約8003の潜在価格は、[0.]
主問題における制約8004の潜在価格は、[1.]
主問題における制約8005の潜在価格は、[0.]
主問題における制約8006の潜在価格は、[1.]
主問題における制約8007の潜在価格は、[0.]
主問題における制約8008の潜在価格は、[1.]
主問題における制約8009の潜在価格は、[0.]
主問題における制約8010の潜在価格は、[1.]
主問題における制約8011の潜在価格は、[0.]
主問題における制約8012の潜在価格は、[1.]
主問題における制約8013の潜在価格は、[0.]
主問題における制約8014の潜在価格は、[1.]
主問題における制約8015の潜在価格は、[0.]
主問題における制約8016の潜在価格は、[1.]
主問題における制約8017の潜在価格は、[0.]
主問題における制約8018の潜在価格は、[1.]
主問題における制約8019の潜在価格は、[0.]
主問題における制約8020の潜在価格は、[1.]
主問題における制約8021の潜在価格は、[0.]
主問題における制約8022の潜在価格は、[1.]
主問題における制約8023の潜在価格は、[0.]
主問題における制約8024の潜在価格は、[1.]
主問題における制約8025の潜在価格は、[0.]
主問題における制約8026の潜在価格は、[1.]
主問題における制約8027の潜在価格は、[0.]
主問題における制約8028の潜在価格は、[1.]
主問題における制約8029の潜在価格は、[0.]
主問題における制約8030の潜在価格は、[1.]
主問題における制約8031の潜在価格は、[0.]


主問題における制約8396の潜在価格は、[1.]
主問題における制約8397の潜在価格は、[0.]
主問題における制約8398の潜在価格は、[1.]
主問題における制約8399の潜在価格は、[0.]
主問題における制約8400の潜在価格は、[1.]
主問題における制約8401の潜在価格は、[0.]
主問題における制約8402の潜在価格は、[1.]
主問題における制約8403の潜在価格は、[0.]
主問題における制約8404の潜在価格は、[1.]
主問題における制約8405の潜在価格は、[0.]
主問題における制約8406の潜在価格は、[1.]
主問題における制約8407の潜在価格は、[0.]
主問題における制約8408の潜在価格は、[1.]
主問題における制約8409の潜在価格は、[0.]
主問題における制約8410の潜在価格は、[1.]
主問題における制約8411の潜在価格は、[0.]
主問題における制約8412の潜在価格は、[1.]
主問題における制約8413の潜在価格は、[0.]
主問題における制約8414の潜在価格は、[1.]
主問題における制約8415の潜在価格は、[0.]
主問題における制約8416の潜在価格は、[1.]
主問題における制約8417の潜在価格は、[0.]
主問題における制約8418の潜在価格は、[1.]
主問題における制約8419の潜在価格は、[0.]
主問題における制約8420の潜在価格は、[1.]
主問題における制約8421の潜在価格は、[0.]
主問題における制約8422の潜在価格は、[1.]
主問題における制約8423の潜在価格は、[0.]
主問題における制約8424の潜在価格は、[1.]
主問題における制約8425の潜在価格は、[0.]
主問題における制約8426の潜在価格は、[1.]
主問題における制約8427の潜在価格は、[0.]
主問題における制約8428の潜在価格は、[1.]
主問題における制約8429の潜在価格は、[0.]
主問題における制約8430の潜在価格は、[1.]
主問題における制約8431の潜在価格は、[0.]
主問題における制約8432の潜在価格は、[1.]
主問題における制約8433の潜在価格は、[0.]
主問題における制約8434の潜在価格は、[1.]
主問題における制約8435の潜在価格は、[0.]


主問題における制約8768の潜在価格は、[1.]
主問題における制約8769の潜在価格は、[0.]
主問題における制約8770の潜在価格は、[1.]
主問題における制約8771の潜在価格は、[0.]
主問題における制約8772の潜在価格は、[1.]
主問題における制約8773の潜在価格は、[0.]
主問題における制約8774の潜在価格は、[1.]
主問題における制約8775の潜在価格は、[0.]
主問題における制約8776の潜在価格は、[1.]
主問題における制約8777の潜在価格は、[0.]
主問題における制約8778の潜在価格は、[1.]
主問題における制約8779の潜在価格は、[0.]
主問題における制約8780の潜在価格は、[1.]
主問題における制約8781の潜在価格は、[0.]
主問題における制約8782の潜在価格は、[1.]
主問題における制約8783の潜在価格は、[0.]
主問題における制約8784の潜在価格は、[1.]
主問題における制約8785の潜在価格は、[0.]
主問題における制約8786の潜在価格は、[1.]
主問題における制約8787の潜在価格は、[0.]
主問題における制約8788の潜在価格は、[1.]
主問題における制約8789の潜在価格は、[0.]
主問題における制約8790の潜在価格は、[1.]
主問題における制約8791の潜在価格は、[0.]
主問題における制約8792の潜在価格は、[1.]
主問題における制約8793の潜在価格は、[0.]
主問題における制約8794の潜在価格は、[1.]
主問題における制約8795の潜在価格は、[0.]
主問題における制約8796の潜在価格は、[1.]
主問題における制約8797の潜在価格は、[0.]
主問題における制約8798の潜在価格は、[1.]
主問題における制約8799の潜在価格は、[0.]
主問題における制約8800の潜在価格は、[1.]
主問題における制約8801の潜在価格は、[0.]
主問題における制約8802の潜在価格は、[1.]
主問題における制約8803の潜在価格は、[0.]
主問題における制約8804の潜在価格は、[1.]
主問題における制約8805の潜在価格は、[0.]
主問題における制約8806の潜在価格は、[1.]
主問題における制約8807の潜在価格は、[0.]


主問題における制約9141の潜在価格は、[0.]
主問題における制約9142の潜在価格は、[1.]
主問題における制約9143の潜在価格は、[0.]
主問題における制約9144の潜在価格は、[1.]
主問題における制約9145の潜在価格は、[0.]
主問題における制約9146の潜在価格は、[1.]
主問題における制約9147の潜在価格は、[0.]
主問題における制約9148の潜在価格は、[1.]
主問題における制約9149の潜在価格は、[0.]
主問題における制約9150の潜在価格は、[1.]
主問題における制約9151の潜在価格は、[0.]
主問題における制約9152の潜在価格は、[1.]
主問題における制約9153の潜在価格は、[0.]
主問題における制約9154の潜在価格は、[1.]
主問題における制約9155の潜在価格は、[0.]
主問題における制約9156の潜在価格は、[1.]
主問題における制約9157の潜在価格は、[0.]
主問題における制約9158の潜在価格は、[1.]
主問題における制約9159の潜在価格は、[0.]
主問題における制約9160の潜在価格は、[1.]
主問題における制約9161の潜在価格は、[0.]
主問題における制約9162の潜在価格は、[1.]
主問題における制約9163の潜在価格は、[0.]
主問題における制約9164の潜在価格は、[1.]
主問題における制約9165の潜在価格は、[0.]
主問題における制約9166の潜在価格は、[1.]
主問題における制約9167の潜在価格は、[0.]
主問題における制約9168の潜在価格は、[1.]
主問題における制約9169の潜在価格は、[0.]
主問題における制約9170の潜在価格は、[1.]
主問題における制約9171の潜在価格は、[0.]
主問題における制約9172の潜在価格は、[1.]
主問題における制約9173の潜在価格は、[0.]
主問題における制約9174の潜在価格は、[1.]
主問題における制約9175の潜在価格は、[0.]
主問題における制約9176の潜在価格は、[1.]
主問題における制約9177の潜在価格は、[0.]
主問題における制約9178の潜在価格は、[1.]
主問題における制約9179の潜在価格は、[0.]
主問題における制約9180の潜在価格は、[1.]


主問題における制約9477の潜在価格は、[0.]
主問題における制約9478の潜在価格は、[1.]
主問題における制約9479の潜在価格は、[0.]
主問題における制約9480の潜在価格は、[1.]
主問題における制約9481の潜在価格は、[0.]
主問題における制約9482の潜在価格は、[1.]
主問題における制約9483の潜在価格は、[0.]
主問題における制約9484の潜在価格は、[1.]
主問題における制約9485の潜在価格は、[0.]
主問題における制約9486の潜在価格は、[1.]
主問題における制約9487の潜在価格は、[0.]
主問題における制約9488の潜在価格は、[1.]
主問題における制約9489の潜在価格は、[0.]
主問題における制約9490の潜在価格は、[1.]
主問題における制約9491の潜在価格は、[0.]
主問題における制約9492の潜在価格は、[1.]
主問題における制約9493の潜在価格は、[0.]
主問題における制約9494の潜在価格は、[1.]
主問題における制約9495の潜在価格は、[0.]
主問題における制約9496の潜在価格は、[1.]
主問題における制約9497の潜在価格は、[0.]
主問題における制約9498の潜在価格は、[1.]
主問題における制約9499の潜在価格は、[0.]
主問題における制約9500の潜在価格は、[1.]
主問題における制約9501の潜在価格は、[0.]
主問題における制約9502の潜在価格は、[1.]
主問題における制約9503の潜在価格は、[0.]
主問題における制約9504の潜在価格は、[1.]
主問題における制約9505の潜在価格は、[0.]
主問題における制約9506の潜在価格は、[1.]
主問題における制約9507の潜在価格は、[0.]
主問題における制約9508の潜在価格は、[1.]
主問題における制約9509の潜在価格は、[0.]
主問題における制約9510の潜在価格は、[1.]
主問題における制約9511の潜在価格は、[0.]
主問題における制約9512の潜在価格は、[1.]
主問題における制約9513の潜在価格は、[0.]
主問題における制約9514の潜在価格は、[1.]
主問題における制約9515の潜在価格は、[0.]
主問題における制約9516の潜在価格は、[1.]


主問題における制約9820の潜在価格は、[1.]
主問題における制約9821の潜在価格は、[0.]
主問題における制約9822の潜在価格は、[1.]
主問題における制約9823の潜在価格は、[0.]
主問題における制約9824の潜在価格は、[1.]
主問題における制約9825の潜在価格は、[0.]
主問題における制約9826の潜在価格は、[1.]
主問題における制約9827の潜在価格は、[0.]
主問題における制約9828の潜在価格は、[1.]
主問題における制約9829の潜在価格は、[0.]
主問題における制約9830の潜在価格は、[1.]
主問題における制約9831の潜在価格は、[0.]
主問題における制約9832の潜在価格は、[1.]
主問題における制約9833の潜在価格は、[0.]
主問題における制約9834の潜在価格は、[1.]
主問題における制約9835の潜在価格は、[0.]
主問題における制約9836の潜在価格は、[1.]
主問題における制約9837の潜在価格は、[0.]
主問題における制約9838の潜在価格は、[1.]
主問題における制約9839の潜在価格は、[0.]
主問題における制約9840の潜在価格は、[1.]
主問題における制約9841の潜在価格は、[0.]
主問題における制約9842の潜在価格は、[1.]
主問題における制約9843の潜在価格は、[0.]
主問題における制約9844の潜在価格は、[1.]
主問題における制約9845の潜在価格は、[0.]
主問題における制約9846の潜在価格は、[1.]
主問題における制約9847の潜在価格は、[0.]
主問題における制約9848の潜在価格は、[1.]
主問題における制約9849の潜在価格は、[0.]
主問題における制約9850の潜在価格は、[1.]
主問題における制約9851の潜在価格は、[0.]
主問題における制約9852の潜在価格は、[1.]
主問題における制約9853の潜在価格は、[0.]
主問題における制約9854の潜在価格は、[1.]
主問題における制約9855の潜在価格は、[0.]
主問題における制約9856の潜在価格は、[1.]
主問題における制約9857の潜在価格は、[0.]
主問題における制約9858の潜在価格は、[1.]
主問題における制約9859の潜在価格は、[0.]


主問題における制約10154の潜在価格は、[1.]
主問題における制約10155の潜在価格は、[0.]
主問題における制約10156の潜在価格は、[1.]
主問題における制約10157の潜在価格は、[0.]
主問題における制約10158の潜在価格は、[1.]
主問題における制約10159の潜在価格は、[0.]
主問題における制約10160の潜在価格は、[1.]
主問題における制約10161の潜在価格は、[0.]
主問題における制約10162の潜在価格は、[1.]
主問題における制約10163の潜在価格は、[0.]
主問題における制約10164の潜在価格は、[1.]
主問題における制約10165の潜在価格は、[0.]
主問題における制約10166の潜在価格は、[1.]
主問題における制約10167の潜在価格は、[0.]
主問題における制約10168の潜在価格は、[1.]
主問題における制約10169の潜在価格は、[0.]
主問題における制約10170の潜在価格は、[1.]
主問題における制約10171の潜在価格は、[0.]
主問題における制約10172の潜在価格は、[1.]
主問題における制約10173の潜在価格は、[0.]
主問題における制約10174の潜在価格は、[1.]
主問題における制約10175の潜在価格は、[0.]
主問題における制約10176の潜在価格は、[1.]
主問題における制約10177の潜在価格は、[0.]
主問題における制約10178の潜在価格は、[1.]
主問題における制約10179の潜在価格は、[0.]
主問題における制約10180の潜在価格は、[1.]
主問題における制約10181の潜在価格は、[0.]
主問題における制約10182の潜在価格は、[1.]
主問題における制約10183の潜在価格は、[0.]
主問題における制約10184の潜在価格は、[1.]
主問題における制約10185の潜在価格は、[0.]
主問題における制約10186の潜在価格は、[1.]
主問題における制約10187の潜在価格は、[0.]
主問題における制約10188の潜在価格は、[1.]
主問題における制約10189の潜在価格は、[0.]
主問題における制約10190の潜在価格は、[1.]
主問題における制約10191の潜在価格は、[0.]
主問題における制約101

主問題における制約10552の潜在価格は、[1.]
主問題における制約10553の潜在価格は、[0.]
主問題における制約10554の潜在価格は、[1.]
主問題における制約10555の潜在価格は、[0.]
主問題における制約10556の潜在価格は、[1.]
主問題における制約10557の潜在価格は、[0.]
主問題における制約10558の潜在価格は、[1.]
主問題における制約10559の潜在価格は、[0.]
主問題における制約10560の潜在価格は、[1.]
主問題における制約10561の潜在価格は、[0.]
主問題における制約10562の潜在価格は、[1.]
主問題における制約10563の潜在価格は、[0.]
主問題における制約10564の潜在価格は、[1.]
主問題における制約10565の潜在価格は、[0.]
主問題における制約10566の潜在価格は、[1.]
主問題における制約10567の潜在価格は、[0.]
主問題における制約10568の潜在価格は、[1.]
主問題における制約10569の潜在価格は、[0.]
主問題における制約10570の潜在価格は、[1.]
主問題における制約10571の潜在価格は、[0.]
主問題における制約10572の潜在価格は、[1.]
主問題における制約10573の潜在価格は、[0.]
主問題における制約10574の潜在価格は、[1.]
主問題における制約10575の潜在価格は、[0.]
主問題における制約10576の潜在価格は、[1.]
主問題における制約10577の潜在価格は、[0.]
主問題における制約10578の潜在価格は、[1.]
主問題における制約10579の潜在価格は、[0.]
主問題における制約10580の潜在価格は、[1.]
主問題における制約10581の潜在価格は、[0.]
主問題における制約10582の潜在価格は、[1.]
主問題における制約10583の潜在価格は、[0.]
主問題における制約10584の潜在価格は、[1.]
主問題における制約10585の潜在価格は、[0.]
主問題における制約10586の潜在価格は、[1.]
主問題における制約10587の潜在価格は、[0.]
主問題における制約10588の潜在価格は、[1.]
主問題における制約10589の潜在価格は、[0.]
主問題における制約105

主問題における制約10913の潜在価格は、[0.]
主問題における制約10914の潜在価格は、[1.]
主問題における制約10915の潜在価格は、[0.]
主問題における制約10916の潜在価格は、[1.]
主問題における制約10917の潜在価格は、[0.]
主問題における制約10918の潜在価格は、[1.]
主問題における制約10919の潜在価格は、[0.]
主問題における制約10920の潜在価格は、[1.]
主問題における制約10921の潜在価格は、[0.]
主問題における制約10922の潜在価格は、[1.]
主問題における制約10923の潜在価格は、[0.]
主問題における制約10924の潜在価格は、[1.]
主問題における制約10925の潜在価格は、[0.]
主問題における制約10926の潜在価格は、[1.]
主問題における制約10927の潜在価格は、[0.]
主問題における制約10928の潜在価格は、[1.]
主問題における制約10929の潜在価格は、[0.]
主問題における制約10930の潜在価格は、[1.]
主問題における制約10931の潜在価格は、[0.]
主問題における制約10932の潜在価格は、[1.]
主問題における制約10933の潜在価格は、[0.]
主問題における制約10934の潜在価格は、[1.]
主問題における制約10935の潜在価格は、[0.]
主問題における制約10936の潜在価格は、[1.]
主問題における制約10937の潜在価格は、[0.]
主問題における制約10938の潜在価格は、[1.]
主問題における制約10939の潜在価格は、[0.]
主問題における制約10940の潜在価格は、[1.]
主問題における制約10941の潜在価格は、[0.]
主問題における制約10942の潜在価格は、[1.]
主問題における制約10943の潜在価格は、[0.]
主問題における制約10944の潜在価格は、[1.]
主問題における制約10945の潜在価格は、[0.]
主問題における制約10946の潜在価格は、[1.]
主問題における制約10947の潜在価格は、[0.]
主問題における制約10948の潜在価格は、[1.]
主問題における制約10949の潜在価格は、[0.]
主問題における制約10950の潜在価格は、[1.]
主問題における制約109

主問題における制約11252の潜在価格は、[1.]
主問題における制約11253の潜在価格は、[0.]
主問題における制約11254の潜在価格は、[1.]
主問題における制約11255の潜在価格は、[0.]
主問題における制約11256の潜在価格は、[1.]
主問題における制約11257の潜在価格は、[0.]
主問題における制約11258の潜在価格は、[1.]
主問題における制約11259の潜在価格は、[0.]
主問題における制約11260の潜在価格は、[1.]
主問題における制約11261の潜在価格は、[0.]
主問題における制約11262の潜在価格は、[1.]
主問題における制約11263の潜在価格は、[0.]
主問題における制約11264の潜在価格は、[1.]
主問題における制約11265の潜在価格は、[0.]
主問題における制約11266の潜在価格は、[1.]
主問題における制約11267の潜在価格は、[0.]
主問題における制約11268の潜在価格は、[1.]
主問題における制約11269の潜在価格は、[0.]
主問題における制約11270の潜在価格は、[1.]
主問題における制約11271の潜在価格は、[0.]
主問題における制約11272の潜在価格は、[1.]
主問題における制約11273の潜在価格は、[0.]
主問題における制約11274の潜在価格は、[1.]
主問題における制約11275の潜在価格は、[0.]
主問題における制約11276の潜在価格は、[1.]
主問題における制約11277の潜在価格は、[0.]
主問題における制約11278の潜在価格は、[1.]
主問題における制約11279の潜在価格は、[0.]
主問題における制約11280の潜在価格は、[1.]
主問題における制約11281の潜在価格は、[0.]
主問題における制約11282の潜在価格は、[1.]
主問題における制約11283の潜在価格は、[0.]
主問題における制約11284の潜在価格は、[1.]
主問題における制約11285の潜在価格は、[0.]
主問題における制約11286の潜在価格は、[1.]
主問題における制約11287の潜在価格は、[0.]
主問題における制約11288の潜在価格は、[1.]
主問題における制約11289の潜在価格は、[0.]
主問題における制約112

主問題における制約11587の潜在価格は、[0.]
主問題における制約11588の潜在価格は、[1.]
主問題における制約11589の潜在価格は、[0.]
主問題における制約11590の潜在価格は、[1.]
主問題における制約11591の潜在価格は、[0.]
主問題における制約11592の潜在価格は、[1.]
主問題における制約11593の潜在価格は、[0.]
主問題における制約11594の潜在価格は、[1.]
主問題における制約11595の潜在価格は、[0.]
主問題における制約11596の潜在価格は、[1.]
主問題における制約11597の潜在価格は、[0.]
主問題における制約11598の潜在価格は、[1.]
主問題における制約11599の潜在価格は、[0.]
主問題における制約11600の潜在価格は、[1.]
主問題における制約11601の潜在価格は、[0.]
主問題における制約11602の潜在価格は、[1.]
主問題における制約11603の潜在価格は、[0.]
主問題における制約11604の潜在価格は、[1.]
主問題における制約11605の潜在価格は、[0.]
主問題における制約11606の潜在価格は、[1.]
主問題における制約11607の潜在価格は、[0.]
主問題における制約11608の潜在価格は、[1.]
主問題における制約11609の潜在価格は、[0.]
主問題における制約11610の潜在価格は、[1.]
主問題における制約11611の潜在価格は、[0.]
主問題における制約11612の潜在価格は、[1.]
主問題における制約11613の潜在価格は、[0.]
主問題における制約11614の潜在価格は、[1.]
主問題における制約11615の潜在価格は、[0.]
主問題における制約11616の潜在価格は、[1.]
主問題における制約11617の潜在価格は、[0.]
主問題における制約11618の潜在価格は、[1.]
主問題における制約11619の潜在価格は、[0.]
主問題における制約11620の潜在価格は、[1.]
主問題における制約11621の潜在価格は、[0.]
主問題における制約11622の潜在価格は、[1.]
主問題における制約11623の潜在価格は、[0.]
主問題における制約11624の潜在価格は、[1.]
主問題における制約116

主問題における制約11916の潜在価格は、[1.]
主問題における制約11917の潜在価格は、[0.]
主問題における制約11918の潜在価格は、[1.]
主問題における制約11919の潜在価格は、[0.]
主問題における制約11920の潜在価格は、[1.]
主問題における制約11921の潜在価格は、[0.]
主問題における制約11922の潜在価格は、[1.]
主問題における制約11923の潜在価格は、[0.]
主問題における制約11924の潜在価格は、[1.]
主問題における制約11925の潜在価格は、[0.]
主問題における制約11926の潜在価格は、[1.]
主問題における制約11927の潜在価格は、[0.]
主問題における制約11928の潜在価格は、[1.]
主問題における制約11929の潜在価格は、[0.]
主問題における制約11930の潜在価格は、[1.]
主問題における制約11931の潜在価格は、[0.]
主問題における制約11932の潜在価格は、[1.]
主問題における制約11933の潜在価格は、[0.]
主問題における制約11934の潜在価格は、[1.]
主問題における制約11935の潜在価格は、[0.]
主問題における制約11936の潜在価格は、[1.]
主問題における制約11937の潜在価格は、[0.]
主問題における制約11938の潜在価格は、[1.]
主問題における制約11939の潜在価格は、[0.]
主問題における制約11940の潜在価格は、[1.]
主問題における制約11941の潜在価格は、[0.]
主問題における制約11942の潜在価格は、[1.]
主問題における制約11943の潜在価格は、[0.]
主問題における制約11944の潜在価格は、[1.]
主問題における制約11945の潜在価格は、[0.]
主問題における制約11946の潜在価格は、[1.]
主問題における制約11947の潜在価格は、[0.]
主問題における制約11948の潜在価格は、[1.]
主問題における制約11949の潜在価格は、[0.]
主問題における制約11950の潜在価格は、[1.]
主問題における制約11951の潜在価格は、[0.]
主問題における制約11952の潜在価格は、[1.]
主問題における制約11953の潜在価格は、[0.]
主問題における制約119

主問題における制約13058の潜在価格は、[1.]
主問題における制約13059の潜在価格は、[0.]
主問題における制約13060の潜在価格は、[1.]
主問題における制約13061の潜在価格は、[0.]
主問題における制約13062の潜在価格は、[1.]
主問題における制約13063の潜在価格は、[0.]
主問題における制約13064の潜在価格は、[1.]
主問題における制約13065の潜在価格は、[0.]
主問題における制約13066の潜在価格は、[1.]
主問題における制約13067の潜在価格は、[0.]
主問題における制約13068の潜在価格は、[1.]
主問題における制約13069の潜在価格は、[0.]
主問題における制約13070の潜在価格は、[1.]
主問題における制約13071の潜在価格は、[0.]
主問題における制約13072の潜在価格は、[1.]
主問題における制約13073の潜在価格は、[0.]
主問題における制約13074の潜在価格は、[1.]
主問題における制約13075の潜在価格は、[0.]
主問題における制約13076の潜在価格は、[1.]
主問題における制約13077の潜在価格は、[0.]
主問題における制約13078の潜在価格は、[1.]
主問題における制約13079の潜在価格は、[0.]
主問題における制約13080の潜在価格は、[1.]
主問題における制約13081の潜在価格は、[0.]
主問題における制約13082の潜在価格は、[1.]
主問題における制約13083の潜在価格は、[0.]
主問題における制約13084の潜在価格は、[1.]
主問題における制約13085の潜在価格は、[0.]
主問題における制約13086の潜在価格は、[1.]
主問題における制約13087の潜在価格は、[0.]
主問題における制約13088の潜在価格は、[1.]
主問題における制約13089の潜在価格は、[0.]
主問題における制約13090の潜在価格は、[1.]
主問題における制約13091の潜在価格は、[0.]
主問題における制約13092の潜在価格は、[1.]
主問題における制約13093の潜在価格は、[0.]
主問題における制約13094の潜在価格は、[1.]
主問題における制約13095の潜在価格は、[0.]
主問題における制約130

主問題における制約13666の潜在価格は、[1.]
主問題における制約13667の潜在価格は、[0.]
主問題における制約13668の潜在価格は、[1.]
主問題における制約13669の潜在価格は、[0.]
主問題における制約13670の潜在価格は、[1.]
主問題における制約13671の潜在価格は、[0.]
主問題における制約13672の潜在価格は、[1.]
主問題における制約13673の潜在価格は、[0.]
主問題における制約13674の潜在価格は、[1.]
主問題における制約13675の潜在価格は、[0.]
主問題における制約13676の潜在価格は、[1.]
主問題における制約13677の潜在価格は、[0.]
主問題における制約13678の潜在価格は、[1.]
主問題における制約13679の潜在価格は、[0.]
主問題における制約13680の潜在価格は、[1.]
主問題における制約13681の潜在価格は、[0.]
主問題における制約13682の潜在価格は、[1.]
主問題における制約13683の潜在価格は、[0.]
主問題における制約13684の潜在価格は、[1.]
主問題における制約13685の潜在価格は、[0.]
主問題における制約13686の潜在価格は、[1.]
主問題における制約13687の潜在価格は、[0.]
主問題における制約13688の潜在価格は、[1.]
主問題における制約13689の潜在価格は、[0.]
主問題における制約13690の潜在価格は、[1.]
主問題における制約13691の潜在価格は、[0.]
主問題における制約13692の潜在価格は、[1.]
主問題における制約13693の潜在価格は、[0.]
主問題における制約13694の潜在価格は、[1.]
主問題における制約13695の潜在価格は、[0.]
主問題における制約13696の潜在価格は、[1.]
主問題における制約13697の潜在価格は、[0.]
主問題における制約13698の潜在価格は、[1.]
主問題における制約13699の潜在価格は、[0.]
主問題における制約13700の潜在価格は、[1.]
主問題における制約13701の潜在価格は、[0.]
主問題における制約13702の潜在価格は、[1.]
主問題における制約13703の潜在価格は、[0.]
主問題における制約137

主問題における制約14519の潜在価格は、[0.]
主問題における制約14520の潜在価格は、[1.]
主問題における制約14521の潜在価格は、[0.]
主問題における制約14522の潜在価格は、[1.]
主問題における制約14523の潜在価格は、[0.]
主問題における制約14524の潜在価格は、[1.]
主問題における制約14525の潜在価格は、[0.]
主問題における制約14526の潜在価格は、[1.]
主問題における制約14527の潜在価格は、[0.]
主問題における制約14528の潜在価格は、[1.]
主問題における制約14529の潜在価格は、[0.]
主問題における制約14530の潜在価格は、[1.]
主問題における制約14531の潜在価格は、[0.]
主問題における制約14532の潜在価格は、[1.]
主問題における制約14533の潜在価格は、[0.]
主問題における制約14534の潜在価格は、[1.]
主問題における制約14535の潜在価格は、[0.]
主問題における制約14536の潜在価格は、[1.]
主問題における制約14537の潜在価格は、[0.]
主問題における制約14538の潜在価格は、[1.]
主問題における制約14539の潜在価格は、[0.]
主問題における制約14540の潜在価格は、[1.]
主問題における制約14541の潜在価格は、[0.]
主問題における制約14542の潜在価格は、[1.]
主問題における制約14543の潜在価格は、[0.]
主問題における制約14544の潜在価格は、[1.]
主問題における制約14545の潜在価格は、[0.]
主問題における制約14546の潜在価格は、[1.]
主問題における制約14547の潜在価格は、[0.]
主問題における制約14548の潜在価格は、[1.]
主問題における制約14549の潜在価格は、[0.]
主問題における制約14550の潜在価格は、[1.]
主問題における制約14551の潜在価格は、[0.]
主問題における制約14552の潜在価格は、[1.]
主問題における制約14553の潜在価格は、[0.]
主問題における制約14554の潜在価格は、[1.]
主問題における制約14555の潜在価格は、[0.]
主問題における制約14556の潜在価格は、[1.]
主問題における制約145

主問題における制約15224の潜在価格は、[1.]
主問題における制約15225の潜在価格は、[0.]
主問題における制約15226の潜在価格は、[1.]
主問題における制約15227の潜在価格は、[0.]
主問題における制約15228の潜在価格は、[1.]
主問題における制約15229の潜在価格は、[0.]
主問題における制約15230の潜在価格は、[1.]
主問題における制約15231の潜在価格は、[0.]
主問題における制約15232の潜在価格は、[1.]
主問題における制約15233の潜在価格は、[0.]
主問題における制約15234の潜在価格は、[1.]
主問題における制約15235の潜在価格は、[0.]
主問題における制約15236の潜在価格は、[1.]
主問題における制約15237の潜在価格は、[0.]
主問題における制約15238の潜在価格は、[1.]
主問題における制約15239の潜在価格は、[0.]
主問題における制約15240の潜在価格は、[1.]
主問題における制約15241の潜在価格は、[0.]
主問題における制約15242の潜在価格は、[1.]
主問題における制約15243の潜在価格は、[0.]
主問題における制約15244の潜在価格は、[1.]
主問題における制約15245の潜在価格は、[0.]
主問題における制約15246の潜在価格は、[1.]
主問題における制約15247の潜在価格は、[0.]
主問題における制約15248の潜在価格は、[1.]
主問題における制約15249の潜在価格は、[0.]
主問題における制約15250の潜在価格は、[1.]
主問題における制約15251の潜在価格は、[0.]
主問題における制約15252の潜在価格は、[1.]
主問題における制約15253の潜在価格は、[0.]
主問題における制約15254の潜在価格は、[1.]
主問題における制約15255の潜在価格は、[0.]
主問題における制約15256の潜在価格は、[1.]
主問題における制約15257の潜在価格は、[0.]
主問題における制約15258の潜在価格は、[1.]
主問題における制約15259の潜在価格は、[0.]
主問題における制約15260の潜在価格は、[1.]
主問題における制約15261の潜在価格は、[0.]
主問題における制約152

主問題における制約15996の潜在価格は、[1.]
主問題における制約15997の潜在価格は、[0.]
主問題における制約15998の潜在価格は、[1.]
主問題における制約15999の潜在価格は、[0.]
主問題における制約16000の潜在価格は、[1.]
主問題における制約16001の潜在価格は、[0.]
主問題における制約16002の潜在価格は、[1.]
主問題における制約16003の潜在価格は、[0.]
主問題における制約16004の潜在価格は、[1.]
主問題における制約16005の潜在価格は、[0.]
主問題における制約16006の潜在価格は、[1.]
主問題における制約16007の潜在価格は、[0.]
主問題における制約16008の潜在価格は、[1.]
主問題における制約16009の潜在価格は、[0.]
主問題における制約16010の潜在価格は、[1.]
主問題における制約16011の潜在価格は、[0.]
主問題における制約16012の潜在価格は、[1.]
主問題における制約16013の潜在価格は、[0.]
主問題における制約16014の潜在価格は、[1.]
主問題における制約16015の潜在価格は、[0.]
主問題における制約16016の潜在価格は、[1.]
主問題における制約16017の潜在価格は、[0.]
主問題における制約16018の潜在価格は、[1.]
主問題における制約16019の潜在価格は、[0.]
主問題における制約16020の潜在価格は、[1.]
主問題における制約16021の潜在価格は、[0.]
主問題における制約16022の潜在価格は、[1.]
主問題における制約16023の潜在価格は、[0.]
主問題における制約16024の潜在価格は、[1.]
主問題における制約16025の潜在価格は、[0.]
主問題における制約16026の潜在価格は、[1.]
主問題における制約16027の潜在価格は、[0.]
主問題における制約16028の潜在価格は、[1.]
主問題における制約16029の潜在価格は、[0.]
主問題における制約16030の潜在価格は、[1.]
主問題における制約16031の潜在価格は、[0.]
主問題における制約16032の潜在価格は、[1.]
主問題における制約16033の潜在価格は、[0.]
主問題における制約160

主問題における制約16680の潜在価格は、[1.]
主問題における制約16681の潜在価格は、[0.]
主問題における制約16682の潜在価格は、[1.]
主問題における制約16683の潜在価格は、[0.]
主問題における制約16684の潜在価格は、[1.]
主問題における制約16685の潜在価格は、[0.]
主問題における制約16686の潜在価格は、[1.]
主問題における制約16687の潜在価格は、[0.]
主問題における制約16688の潜在価格は、[1.]
主問題における制約16689の潜在価格は、[0.]
主問題における制約16690の潜在価格は、[1.]
主問題における制約16691の潜在価格は、[0.]
主問題における制約16692の潜在価格は、[1.]
主問題における制約16693の潜在価格は、[0.]
主問題における制約16694の潜在価格は、[1.]
主問題における制約16695の潜在価格は、[0.]
主問題における制約16696の潜在価格は、[1.]
主問題における制約16697の潜在価格は、[0.]
主問題における制約16698の潜在価格は、[1.]
主問題における制約16699の潜在価格は、[0.]
主問題における制約16700の潜在価格は、[1.]
主問題における制約16701の潜在価格は、[0.]
主問題における制約16702の潜在価格は、[1.]
主問題における制約16703の潜在価格は、[0.]
主問題における制約16704の潜在価格は、[1.]
主問題における制約16705の潜在価格は、[0.]
主問題における制約16706の潜在価格は、[1.]
主問題における制約16707の潜在価格は、[0.]
主問題における制約16708の潜在価格は、[1.]
主問題における制約16709の潜在価格は、[0.]
主問題における制約16710の潜在価格は、[1.]
主問題における制約16711の潜在価格は、[0.]
主問題における制約16712の潜在価格は、[1.]
主問題における制約16713の潜在価格は、[0.]
主問題における制約16714の潜在価格は、[1.]
主問題における制約16715の潜在価格は、[0.]
主問題における制約16716の潜在価格は、[1.]
主問題における制約16717の潜在価格は、[0.]
主問題における制約167

主問題における制約17268の潜在価格は、[1.]
主問題における制約17269の潜在価格は、[0.]
主問題における制約17270の潜在価格は、[1.]
主問題における制約17271の潜在価格は、[0.]
主問題における制約17272の潜在価格は、[1.]
主問題における制約17273の潜在価格は、[0.]
主問題における制約17274の潜在価格は、[1.]
主問題における制約17275の潜在価格は、[0.]
主問題における制約17276の潜在価格は、[1.]
主問題における制約17277の潜在価格は、[0.]
主問題における制約17278の潜在価格は、[1.]
主問題における制約17279の潜在価格は、[0.]
主問題における制約17280の潜在価格は、[1.]
主問題における制約17281の潜在価格は、[0.]
主問題における制約17282の潜在価格は、[1.]
主問題における制約17283の潜在価格は、[0.]
主問題における制約17284の潜在価格は、[1.]
主問題における制約17285の潜在価格は、[0.]
主問題における制約17286の潜在価格は、[1.]
主問題における制約17287の潜在価格は、[0.]
主問題における制約17288の潜在価格は、[1.]
主問題における制約17289の潜在価格は、[0.]
主問題における制約17290の潜在価格は、[1.]
主問題における制約17291の潜在価格は、[0.]
主問題における制約17292の潜在価格は、[1.]
主問題における制約17293の潜在価格は、[0.]
主問題における制約17294の潜在価格は、[1.]
主問題における制約17295の潜在価格は、[0.]
主問題における制約17296の潜在価格は、[1.]
主問題における制約17297の潜在価格は、[0.]
主問題における制約17298の潜在価格は、[1.]
主問題における制約17299の潜在価格は、[0.]
主問題における制約17300の潜在価格は、[1.]
主問題における制約17301の潜在価格は、[0.]
主問題における制約17302の潜在価格は、[1.]
主問題における制約17303の潜在価格は、[0.]
主問題における制約17304の潜在価格は、[1.]
主問題における制約17305の潜在価格は、[0.]
主問題における制約173

主問題における制約18321の潜在価格は、[0.]
主問題における制約18322の潜在価格は、[1.]
主問題における制約18323の潜在価格は、[0.]
主問題における制約18324の潜在価格は、[1.]
主問題における制約18325の潜在価格は、[0.]
主問題における制約18326の潜在価格は、[1.]
主問題における制約18327の潜在価格は、[0.]
主問題における制約18328の潜在価格は、[1.]
主問題における制約18329の潜在価格は、[0.]
主問題における制約18330の潜在価格は、[1.]
主問題における制約18331の潜在価格は、[0.]
主問題における制約18332の潜在価格は、[1.]
主問題における制約18333の潜在価格は、[0.]
主問題における制約18334の潜在価格は、[1.]
主問題における制約18335の潜在価格は、[0.]
主問題における制約18336の潜在価格は、[1.]
主問題における制約18337の潜在価格は、[0.]
主問題における制約18338の潜在価格は、[1.]
主問題における制約18339の潜在価格は、[0.]
主問題における制約18340の潜在価格は、[1.]
主問題における制約18341の潜在価格は、[0.]
主問題における制約18342の潜在価格は、[1.]
主問題における制約18343の潜在価格は、[0.]
主問題における制約18344の潜在価格は、[1.]
主問題における制約18345の潜在価格は、[0.]
主問題における制約18346の潜在価格は、[1.]
主問題における制約18347の潜在価格は、[0.]
主問題における制約18348の潜在価格は、[1.]
主問題における制約18349の潜在価格は、[0.]
主問題における制約18350の潜在価格は、[1.]
主問題における制約18351の潜在価格は、[0.]
主問題における制約18352の潜在価格は、[1.]
主問題における制約18353の潜在価格は、[0.]
主問題における制約18354の潜在価格は、[1.]
主問題における制約18355の潜在価格は、[0.]
主問題における制約18356の潜在価格は、[1.]
主問題における制約18357の潜在価格は、[0.]
主問題における制約18358の潜在価格は、[1.]
主問題における制約183

主問題における制約18636の潜在価格は、[1.]
主問題における制約18637の潜在価格は、[0.]
主問題における制約18638の潜在価格は、[1.]
主問題における制約18639の潜在価格は、[0.]
主問題における制約18640の潜在価格は、[1.]
主問題における制約18641の潜在価格は、[0.]
主問題における制約18642の潜在価格は、[1.]
主問題における制約18643の潜在価格は、[0.]
主問題における制約18644の潜在価格は、[1.]
主問題における制約18645の潜在価格は、[0.]
主問題における制約18646の潜在価格は、[1.]
主問題における制約18647の潜在価格は、[0.]
主問題における制約18648の潜在価格は、[1.]
主問題における制約18649の潜在価格は、[0.]
主問題における制約18650の潜在価格は、[1.]
主問題における制約18651の潜在価格は、[0.]
主問題における制約18652の潜在価格は、[1.]
主問題における制約18653の潜在価格は、[0.]
主問題における制約18654の潜在価格は、[1.]
主問題における制約18655の潜在価格は、[0.]
主問題における制約18656の潜在価格は、[1.]
主問題における制約18657の潜在価格は、[0.]
主問題における制約18658の潜在価格は、[1.]
主問題における制約18659の潜在価格は、[0.]
主問題における制約18660の潜在価格は、[1.]
主問題における制約18661の潜在価格は、[0.]
主問題における制約18662の潜在価格は、[1.]
主問題における制約18663の潜在価格は、[0.]
主問題における制約18664の潜在価格は、[1.]
主問題における制約18665の潜在価格は、[0.]
主問題における制約18666の潜在価格は、[1.]
主問題における制約18667の潜在価格は、[0.]
主問題における制約18668の潜在価格は、[1.]
主問題における制約18669の潜在価格は、[0.]
主問題における制約18670の潜在価格は、[1.]
主問題における制約18671の潜在価格は、[0.]
主問題における制約18672の潜在価格は、[1.]
主問題における制約18673の潜在価格は、[0.]
主問題における制約186

In [ ]:
# 最適解
for var in whole_y.getVars():
    print(var.varName, var.X)

### 4. 全体のPrimalの最適解を得る

In [ ]:
for i, constr in enumerate(whole_y.getConstrs()):
    print(constr.Pi)

In [ ]:
for var in whole_x.getVars():
    print(var.varName, var.X)